### ISSUE TITLE
cloud.189.cn

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1475] opened 2021-07-08 14:23 UTC
@adguard-bot commented on [Sun Jun 27 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86947)

### Issue URL (Incorrect Blocking)
 [https://cloud.189.cn/web/main/file](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcloud.189.cn%2Fweb%2Fmain%2Ffile)
### Comment
> 只要开启防护就加载不进去 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/YrRu1FS.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/R62MpQj.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1
Browser: | Edge
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>EasyList
Userscripts: | disabled
Referrer: | [https://cloud.189.cn/web/share?code=uiMzEzuE7jMn](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcloud.189.cn%2Fweb%2Fshare%3Fcode%3DuiMzEzuE7jMn)

---

@adguard-bot commented on [Thu Jul 08 2021](https://github.com/AdguardTeam/AdguardFilters/issues/86947#issuecomment-876463596)

### Issue URL (Incorrect Blocking)
 [https://cloud.189.cn/web/share?code=NvQnyeiiY3In](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcloud.189.cn%2Fweb%2Fshare%3Fcode%3DNvQnyeiiY3In)
### Comment
> 开启adguard，访问https://cloud.189.cn/web/share?code=NvQnyeiiY3In，无法打开分享密码输入框。

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/czjrew3.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/hubScem.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.6.1 (build 3583, CL 1.7.221)
Browser: | Edge
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>ChinaList+EasyList
Userscripts: | disabled

**Comment by AdamWr** [comment] 2021-07-08 14:27
Steps to reproduce:
1. Disable this rule (from AdGuard Base filter):
`@@||cloud.189.cn^$elemhide,jsinject,extension`
2. Go here - [https://cloud.189.cn/web/share?code=NvQnyeiiY3In](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcloud.189.cn%2Fweb%2Fshare%3Fcode%3DNvQnyeiiY3In)

Website stucks on loading.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/124938981-0baac300-e009-11eb-935c-d4983ab32667.png)

</details>

**Comment by sfionov** [comment] 2021-11-28 21:52
Yet another HTML xhr inject.

There was problem with XHR detection in browsers released in years 2017-2019, when `Origin` appeared in regular requests, and `Sec-Fetch-Dest` was not deployed yet.

The workaround is:
```
@@||cloud.189.cn/web/subapp/share.html^$xmlhttprequest,elemhide,jsinject,extension
```

@ameshkov May we whitelist such xhrs by default if `Sec-Fetch-Dest` is detected? I think that we may ask filters devs or QA to test surfing with `@@$xmlhttprequest,elemhide,jsinject,extension` and report if it results in ads shown :)

**Comment by ameshkov** [comment] 2021-11-29 06:14
@sxgunchenko It will definitely result in quite a lot of unblocked stuff. I suggest solving these issues selectively on the filter lists side.

If this is not a bug, let’s close the issue.

**Closed** 2021-11-29 15:47 UTC
Labels: bug, Resolution: Won't Fix, Status: Resolved, Version: CoreLibs v1.9
