### ISSUE TITLE
Use $domain modifier for target domains only in non-domain rules

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1354] opened 2020-10-06 08:18 UTC
### Steps to reproduce

1. Add these rules:
```
||example.org^$replace=/<h1>[\s\S]*?<\/h1>/<iframe src="https:\/\/www.youtube.com\/embed\/dQw4w9WgXcQ"><\/iframe>/
||youtube.com/embed/
@@||youtube.com/embed/$domain=youtube.com|whatever.test
```
2. Go here - http://example.org/
### Expected behavior

Iframe with youtube should be blocked.

### Actual behavior

Requests are unblocked and iframe is not blocked.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/95175679-1d321680-07bc-11eb-9a0e-af609e75ad1f.png)

</details>

### Your environment

* AdGuard for Windows version 7.5 nightly 33 (build 3407, CL 1.7.114)

**Comment by sxgunchenko** [comment] 2020-10-06 08:32
It seems like it is #1202 case. So the domain modifier matches not only the referrer domain but the target one also.

**Comment by AdamWr** [comment] 2020-10-06 08:39
So, as far as I understand it's a correct behavior?

I checked it with another ad blockers (Adblock Plus and uBlock Origin) and it seems that both block this iframe with mentioned rules.

**Comment by sxgunchenko** [comment] 2020-10-06 08:47
Yes, it is or at least it is intended behavior.
By the way, there is (still not merged) PR which adds the description: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/654/files

**Comment by AdamWr** [comment] 2020-10-06 09:06
Maybe I don't understand something, but it's about blocking rules, not exceptions.
So what rule I should add if I want to unblock `youtube.com/embed/` only on `youtube.com` and block it on any other website (without using `||youtube.com/embed/$domain=~youtube.com`)?

If I'm not wrong, at the moment rule like this `@@||youtube.com/embed/$domain=youtube.com` is the same as just `@@||youtube.com/embed/`, what I think is strange.

**Comment by AdamWr** [comment] 2020-10-06 09:15
The real case (this is a test website, but anyway) is here (`canyoublockit.com`) - https://github.com/AdguardTeam/AdguardFilters/issues/65132 and related to this (`audiogon.com`) - https://github.com/AdguardTeam/AdguardFilters/issues/64518

In Base filter is rule like this:
`@@||cdn.bannersnack.com/banners/$image,subdocument,domain=cdn.bannersnack.com|audiogon.com`
and it unblocks `bannersnack.com` ads on `canyoublockit.com` (and any other website I guess) due `$domain=cdn.bannersnack.com`, for me it looks weird.

It seems that we need to change exception rule to:
```
@@||cdn.bannersnack.com/banners/$~third-party,image,subdocument
@@||cdn.bannersnack.com/banners/$image,subdocument,domain=audiogon.com
```
and it will be works as expected.

**Comment by ameshkov** [comment] 2020-10-06 12:11
> If I'm not wrong, at the moment rule like this @@||youtube.com/embed/$domain=youtube.com is the same as just @@||youtube.com/embed/, what I think is strange.

Makes sense.

Let's make the scope of this $domain modifier quirk even narrower.

$domain modifier may be interpreted as a target domain when all these are true:

1. The target is of "DOCUMENT" type
2. The pattern does not target any domain (e.g. it does not start with `||`)
3. We should support TLD in $document (see [here](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1522#issuecomment-588219110))

**Closed** 2021-08-10 09:14 UTC
Labels: enhancement, Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.8, Medium
