### ISSUE TITLE
support.motto.nl

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/CoreLibs#811] opened 2019-03-20 19:09 UTC
@adguard-bot commented on [Wed Mar 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31316)

### Issue URL (Incorrect Blocking)
[https://support.motto.nl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsupport.motto.nl%2F)
### Comment
Username: @Yevhen1996
> The website is broken when AdGuard protection is enabled. It's loading very slowly and the frame part of the registration is not visible. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/jTK3Dsj.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/kwKHQvN.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.0.0.521
Browser: | Chrome
Filters: | AdGuard Russian,<br>AdGuard Base,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>Malware Domains

---

@Alex-302 commented on [Wed Mar 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/31316#issuecomment-474974741)

Cannot reproduce. Is it caused by filters?

**Comment by TheHasagi** [comment] 2019-03-20 19:10
This website cannot be opened with AdGurad for Mac 2.0.0.521.

Working fine only if an extension is enabled.

**Comment by Yevhen1996** [comment] 2019-03-20 20:00
Steps to reproduce: 
1) Turn on AdGuard for Mac
2) Open the website: https://support.motto.nl/ (it's loading for quite a while and then gives an error "This site can’t be reached" or just shows the login field without the visual frame.
3) You turn off AdGuard
4) The page is loaded immediately

**Comment by sfionov** [comment] 2019-03-28 16:57
Duplicate of #823. Fixed in CL 1.3.241.

**Closed by sfionov** 2019-03-28 16:57 UTC
Labels: P2: High, bug
