### ISSUE TITLE
AGProxyFilter::processHttpResponseBody: AGProxyFilter.cpp:744 assertion (0) failed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#410] opened 2018-07-24 12:51 UTC
https://sentry.adguard.com/adg/adguard-android-rs/issues/6656/

**Comment by sfionov** [comment] 2018-07-24 12:52
Duplicate of #406

**Closed by sfionov** 2018-07-24 12:52 UTC
Labels: P3: Medium, bug
