### ISSUE TITLE
AG for Mac breaks captive portal on Mac

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#612] opened 2018-11-13 11:59 UTC
Absolutely nothing helpful in the log. Captive portal window shows an error -- cannot load page.

**Comment by sfionov** [comment] 2018-11-29 13:34
Seems that Captive portals with correct HTTPS domains work correctly.
The problem may be with HTTPS with IP address - e.g. IP exclusion is auto-added but we change that IP on kext level.

**Comment by djpadz** [comment] 2018-12-10 08:07
An observation from my end...  If I tell AG to not filter Safari, then captive portals (via Captive Network Assistant) start working.  Obviously, this isn't what I want, but I find it odd that Captive Network Assistant "looks like" Safari, to AG.

Incidentally, adding Captive Network Assistant to the application list, and leaving it unchecked doesn't fix the problem.

**Comment by ameshkov** [comment] 2018-12-10 08:40
@djpadz are you on the stable version of AG or on the nightly build?

**Comment by djpadz** [comment] 2018-12-10 08:53
@ameshkov I'm on the stable build.  Should I switch to the nightly?

**Comment by ameshkov** [comment] 2018-12-10 08:57
@djpadz it is possible that the issue is resolved in the nightly (at least we could not reproduce it anymore).

You can find the nightly build installer here:
https://adguard.com/en/beta.html

**Comment by djpadz** [comment] 2018-12-10 09:07
Cool, I'll check it out and report back!

**Comment by sfionov** [comment] 2018-12-10 09:36
@djpadz 
You can switch on debug logging from menu (Settings->Advanced->Logging level->Debug) before login and use Console app to find them (com.adguard.Adguard).
Also, it will be interesting to see what is shown on bottom line of Wi-Fi login window when Adguard on and off. Especially, is there an IP address or some name.

P.S. Don't forget to switch off debug logging after the tests - debug logs are slowing down the AdGuard.

**Comment by sfionov** [comment] 2018-12-10 09:40
@djpadz Forgot to say: Please send logs to devteam@adguard.com

**Comment by djpadz** [comment] 2018-12-10 19:09
Got it.  I won't be back on a captive network for another 12 hours, but I'll try to get to it tonight.

**Comment by djpadz** [comment] 2018-12-18 08:16
@sfionov Sorry for the delay.  I submitted a bug report.  Will the logs that are attached to it, have the info you needed?

**Comment by djpadz** [comment] 2018-12-18 09:04
@ameshkov Hmmm...  I submitted it via the Support option in the gear menu.  Failing that, which logs should I collect, and send over?

**Comment by ameshkov** [comment] 2018-12-18 09:05
> @ameshkov Hmmm... I submitted it via the Support option in the gear menu. Failing that, which logs should I collect, and send over?

See the @sfionov message: https://github.com/AdguardTeam/CoreLibs/issues/612#issuecomment-445750228

You can switch AG to a debug-level logging and then manually grab the logs using the Console.app

**Comment by djpadz** [comment] 2018-12-18 17:10
@ameshkov Apologies; I didn't catch the whole message there.  I've emailed the logs, but I don't think there's anything useful in them.  The bottom of the captive portal window flashes "captive.apple.com", and then goes blank.

**Comment by ameshkov** [comment] 2018-12-29 15:11
Merging here:
https://github.com/AdguardTeam/AdguardForMac/issues/394

**Comment by ameshkov** [comment] 2019-01-14 18:40
@sfionov if you need any help, I am having troubles with this captive portal issue right now and I can collect logs for you.

**Comment by sfionov** [comment] 2019-01-18 14:02
@ameshkov It will be good! AdGuard debug logs + wireshark dump + page to where http://captive.apple.com/hotspot-detect.html is being redirected (e.g. from Safari developer tools)

**Comment by ameshkov** [comment] 2019-01-28 20:10
@seanob86 thank you so much!

@sfionov @szolin guys, this part of the log seems to be relevant (a few connections by `captiveagent`):

```
2019-01-25 09:11:09:268 BEGIN tl_attach_fn_ip4  - so: 0x3F748C80 pid=1005, name=captiveagent
2019-01-25 09:11:09:268 tl_attach_fn  - so: 0x3F748C80 pid=1005, name=captiveagent
2019-01-25 09:11:09:268 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:268 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:268 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:269 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:269 tl_connect_out_fn - so: 0x3F748C80 pid=1005, f=IPv4, src=0.0.0.0:0, dst=17.253.69.208:80, name=captiveagent
2019-01-25 09:11:09:269 tl_connect_out_fn  - before rule_find so: 0x3F748C80
2019-01-25 09:11:09:269 rule_find entered
2019-01-25 09:11:09:269 rule_find before loop - so: 0x3F748C80 pid=1005, f=IPv4, src=0.0.0.0:0, dst=17.253.69.208:80, name=captiveagent
2019-01-25 09:11:09:269 no rule
2019-01-25 09:11:09:278 sock_evt_connecting  so: 0x3F748C80
2019-01-25 09:11:09:278 sock_evt_connecting with SRC - so: 0x3F748C80 pid=1005, f=IPv4, src=10.27.24.19:49164, dst=unknown:0, name=captiveagent
2019-01-25 09:11:09:315 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:316 setsockopt_redirected_internal - so: 0x3F748C80
2019-01-25 09:11:09:316 setsockopt_redirected_internal - so: 0x3F748C80
```

Later I see another TCP connection now from `com.apple.WebKit` to the same IP:port:
```
2019-01-25 09:11:10:558 tl_connect_out_fn - so: 0x3F748C80 pid=1012, f=IPv4, src=0.0.0.0:0, dst=17.253.69.208:80, name=com.apple.WebKit
2019-01-25 09:11:10:558 tl_connect_out_fn ksf_already_redirected! - so: 0x3F748C80 pid=1012, f=IPv4, src=0.0.0.0:0, dst=17.253.69.208:80, name=com.apple.WebKit
```

I am pretty sure this is `captive.apple.com:80` connection we were looking for. However, I don't see any information about this connection outside of the Kext log.

**Comment by ameshkov** [comment] 2019-01-29 08:13
@seanob86 while I am waiting for @sfionov to look into it, could you please check one thing for us?

Add this rule to the user filter: `@@17.253.*$network`

It will completely disable filtering for `17.253.*` subnet and it will check my idea of what's causing the issue.

**Comment by seanob86** [comment] 2019-01-29 09:08
OK no problem. Please give me a couple of days to get back on that open network.
Do you require additional logs after adding the rule or just a simple "it worked/didn't work"?

**Comment by ameshkov** [comment] 2019-01-29 09:16
> Do you require additional logs after adding the rule or just a simple "it worked/didn't work"?

Yeah, it will help a lot

**Comment by seanob86** [comment] 2019-01-31 00:16
I have emailed `devteam@adguard.com` with logs after attempting again on open wifi network.
Unfortunately, even with the rule added to the user filter the captive portal window could not load.

<img width="1034" alt="screen shot 2019-01-31 at 09 07 05" src="https://user-images.githubusercontent.com/45988261/52021478-3bc31300-24ed-11e9-998c-3e0ba005fabc.png">
<img width="1042" alt="screen shot 2019-01-31 at 09 06 28" src="https://user-images.githubusercontent.com/45988261/52021482-3f569a00-24ed-11e9-8916-48de303092a3.png">

**Comment by ameshkov** [comment] 2019-02-11 09:55
Good news, I think we have finally figured what's the problem and how to fix it.

The next nightly update should work okay, I'll post a link here when it's ready.

**Comment by ameshkov** [comment] 2019-02-18 13:24
@seanob86 @djpadz hi guys, we've rolled the new nightly last week (version .511), the captive portal issue should be fixed there. Could you please check it?

**Comment by djpadz** [comment] 2019-02-18 18:12
@ameshkov I'll be able to check it out later tonight.  Fingers crossed! :-)

**Comment by djpadz** [comment] 2019-02-19 07:02
@ameshkov Just tried it on a portal that hasn't worked in the past.  It works now!!!  Huzzah!

**Comment by seanob86** [comment] 2019-02-19 07:10
I’ll respond with my test results tomorrow.

**Comment by seanob86** [comment] 2019-02-20 00:14
Nightly v. .511 now works! No more issues loading the captive network portal window. Good job guys!

**Comment by ameshkov** [comment] 2019-02-20 07:39
@djpadz @seanob86  awesome, thank you for checking it!

**Comment by jace** [comment] 2021-08-24 13:25
I’m experiencing this problem with Adguard 2.5.5.1002 nightly on macOS Big Sur. I have to disable AdGuard before joining a public WiFi network and enable it again after the captive portal login process. I do not have DNS filtering enabled.

**Comment by smark91** [comment] 2022-02-08 12:35
Any update?

**Comment by cryptopatik22** [comment] 2022-10-08 11:35
@ameshkov @sfionov the issue is back, here are the logs:
ticket number is 654194
[adguard_logs_20221007102250.zip](https://github.com/AdguardTeam/CoreLibs/files/9739098/adguard_logs_20221007102250.zip)

**Comment by cryptopatik22** [comment] 2022-10-08 11:35
please let me know if something else is required

**Closed** 2022-10-12 21:18 UTC
Labels: bug, P2: High, Mac, Resolution: Fixed, Status: Resolved

**Comment by jace** [comment] 2022-10-18 05:35
Is there a release number for the fix?
