### ISSUE TITLE
Regexp rule doesn't match url

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1311] opened 2020-07-07 15:20 UTC
Cannot exclude URL using regexp.
I want to exlude URL like that using regexp to match last 5 digits:
`https://producebreed.com/r6uZwxSoabpA9Ui2/14617`

Steps to reproduce:
1. Add `@@torrent-download.net^$content` to user rules;
add
2. Disable `@@14617$xmlhttprequest,script,other,third-party,domain=torrent-download.net|mac-torrent-download.net` in Base filter;
3. Go to https://mac-torrent-download.net/

On screenshot you can see two regex rules, and both do not unblock the second request
![image](https://user-images.githubusercontent.com/8361299/86803146-65874e80-c07e-11ea-9507-e8c8a9801f76.png)

AdGuard for MacOS 2.4.9 CL-1.5.269

**Comment by sxgunchenko** [comment] 2020-07-09 07:24
Cannot reproduce with CoreLibs 1.6

**Comment by sxgunchenko** [comment] 2020-07-09 16:16
I was wrong, it's reproducible. Fixed in core/pull-requests/1980.

**Closed** 2020-08-31 09:42 UTC
Labels: P2: High, Resolution: Fixed, Status: Resolved, bug
