### ISSUE TITLE
aztelekom.az cannot be opened with 'Protect from DPI' enabled

### ISSUE THREAD

**Issue by mrrtarlan** [AdguardTeam/CoreLibs#1639] opened 2022-05-22 12:28 UTC
![screenshot_4](https://user-images.githubusercontent.com/105488188/169695168-67bb2fee-1698-4812-9831-aa4de99b469c.png)

**Comment by zubrRB** [comment] 2022-05-22 12:33
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/1615

**Comment by sfionov** [comment] 2022-06-14 07:57
Thank you for info! Closing this in favor of #1645

**Closed** 2022-06-14 07:57 UTC
