### ISSUE TITLE
Tik-tok live blocked

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [AdguardTeam/CoreLibs#1473] opened 2021-07-06 14:51 UTC
Api: 26
android 8.0
abis: arm64-v8a
kernel: 4.4.23+

com.adguard.android
Version 4.0.56 (10000566)

link apps: https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically

step to reproduce: 
open tik-tok app go top left Live nothing live load because quic protocol blocked , tik-tok use quic for live

**Comment by sfionov** [comment] 2021-07-06 15:10
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3866

Let's wait for the next nightly.

**Closed by sfionov** 2021-07-06 15:10 UTC

**Comment by sfionov** [comment] 2021-07-09 21:18
@Disqu3-mirOir-qt 4.0 nightly 16 is out with `pref.quic.bypass.packages` low-level setting. It includes applications that has broken functionality due to QUIC. We are working on QUIC filtering right now, so in the future there will be better solution.
