### ISSUE TITLE
Cannot open the website when AG for Mac is enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1244] opened 2020-01-19 16:37 UTC
URL: `https://app.scottscheapflights.com/login`

I am getting "ERR_EMPTY_RESPONSE" there.

The website returns `Connection: close` so I guess something is wrong with the packets order.

**Comment by sfionov** [comment] 2020-01-19 17:38
Duplicate of #1238

**Closed by sfionov** 2020-01-19 17:38 UTC
Labels: P2: High, bug
