### ISSUE TITLE
Skype doesn't work unless manually excluded in advanced settings

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1103] opened 2019-08-30 13:57 UTC
@COOLak commented on [Sun Aug 18 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2908)

### Steps to reproduce

1. Open Skype with protection enabled
2. See that online statuses will not load for your contacts, you can't send/receive messages and can't update Skype.

### Expected behavior
Everything works "out of the box".

### Actual behavior
Everything works only after manually adding Skype's full path into Exceptions field in the Advanced Settings.

### Your environment

* Operating system and version: Windows 7, AdGuard 7.1.2898 nightly

---

@COOLak commented on [Thu Aug 29 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2908#issuecomment-526250180)

Weird, nobody has taken on this. Couldn't you reproduce this issue?

---

@zzebrum commented on [Fri Aug 30 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2908#issuecomment-526606755)

@COOLak sorry for late reply. 

So far I can not confirm the problem on the latest AdGuard nightly and Skype 8.51.0.92 windows 7

Please, change the logging level to debug, reproduce the issue and send log files to devteam[at]adguard[dot]com

**Comment by Vitalik93** [comment] 2019-08-30 17:18
Не знаю как у других, у мня со статусами и сообщениями всё хорошо, не работает только обновление.

**Comment by Chinaski1** [comment] 2019-09-09 14:32
Added two packs of logs in *NCloud*

**Comment by Vitalik93** [comment] 2019-09-18 17:33
Короче на 7.2 всё то же самое...

**Comment by Chinaski1** [comment] 2019-09-19 08:54
Logs in **NCloud**

**Comment by Vitalik93** [comment] 2021-03-22 21:43
Ну что там с решением проблемы? Просто интересно уже, чем эпопея закончится, которая идёт больше года...

**Comment by ngorskikh** [comment] 2022-01-18 15:27
Skype is closing some of its TLS connections right after the handshake. Probably some sort of certificate pinning. Adding `download.skype.com` to HTTPS exclusions fixes the update issue. Other issues: can't reproduce.

**Closed** 2022-09-19 09:42 UTC
Labels: Windows, compatibility, Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.10
