### ISSUE TITLE
A userscript does not work correctly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#186] opened 2018-03-16 11:09 UTC
@freezewind commented on [Thu Nov 16 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2011)

### Steps to reproduce
1. Install the userscripts from https://greasyfork.org/en/scripts/292-my-novel-reader
2. Go to https://www.snwx8.com/book/144/144937/56698154.html
3. Click the icon ![default](https://user-images.githubusercontent.com/3954389/32876582-58785db2-ca52-11e7-9fc8-ee9cea22df18.png)  in right bottom corner
4. Go to the end of page, and then the script will load the next page

### Expected behavior
Showing the correct text
Showing the icon in right bottom corner after step 3
![default](https://user-images.githubusercontent.com/3954389/32876754-11c510da-ca53-11e7-8ad5-7a191937d00d.png)

### Actual behavior
Showing the garbled text
Missing the icon in right bottom corner step 3
![default](https://user-images.githubusercontent.com/3954389/32876666-c0374652-ca52-11e7-8b38-12e7904802c5.png)

### Your environment
Firefox 56
Adguard 6.2.436.2170
Win 10 v. 1709 build 16299.64

---

@ameshkov commented on [Thu Nov 30 2017](https://github.com/AdguardTeam/AdguardForWindows/issues/2011#issuecomment-348194408)

Seems like an issue with encoding

**Comment by szolin** [comment] 2018-09-03 16:51
Reproduced.  The problem may be in userscript-wrapper, because our proxy server sends what seems to be correct Chinese text in response to this xhr request from browser:

`https://local.adguard.com/adguard-ajax-api/api?type=gm-xml-http-request&unique_name=My%20Novel%20Reader&url=https%3A%2F%2Fwww.snwx8.com%2Fbook%2F144%2F144937%2F56698155.html&data=&headers=&method=GET&overridemimetype=text%2Fhtml%3Bcharset%3DGBK`

**Comment by ameshkov** [comment] 2018-09-03 16:54
Reassigned to @maximtop , but the issue is not major, hurry not

**Comment by wanesoft** [comment] 2020-08-07 13:33
1. https://www.snwx8.com removed to https://www.snwx3.com so, the userscript's line 342 should be exchanged.
2. behavior not reproduced 

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/42610583/89650602-5e48a000-d8cb-11ea-8181-5567987a527b.png">

**Comment by freezewind** [comment] 2020-08-07 19:44
I tested it again. It still reproduced. I think you didn't go to the end of page or you read a page that doesn't has next page.
Tested page:
https://www.snwx3.com/book/144/144937/56698154.html
![image](https://user-images.githubusercontent.com/3954389/89682413-89bb9280-d8ab-11ea-8845-7a5f4bb7d13c.png)
https://www.sqsxs.com/book/0/2/4.html
![image](https://user-images.githubusercontent.com/3954389/89682519-b7084080-d8ab-11ea-8104-6639a0b81f70.png)

**Comment by wanesoft** [comment] 2020-08-19 13:52
> @wanesoft I tested it again. It still reproduced. I think you didn't go to the end of page or you read a page that doesn't has next page.
> Tested page:
> https://www.sqsxs.com/book/0/2/4.html

We're back to this problem, here's the latest news. First. The request and response appear normal. The encoding breaks at the moment of data transfer from the browser to our script, but we see a normal page in the preview. I can't explain it yet.

![image](https://user-images.githubusercontent.com/42610583/90643343-2b43cc00-e23c-11ea-94a1-60a5d707c64e.png)

Second. We are closing the connection, but the script needs to save it, so even if the encoding problem is solved, the third page will not load.

**Comment by wanesoft** [comment] 2020-08-20 10:51
encoding fix
core/pull-requests/2084

**Comment by freezewind** [comment] 2020-09-03 10:03
@wanesoft 
Thank you for your work. The encoding and the third page are loaded.
But, it is still missing the icon in right bottom corner that showed in Expected behavior.

**Comment by freezewind** [comment] 2020-09-13 09:46
Anyone here? At least tell me that you guys know that it still a issue left here. I am worry no one here because it marked as Resolved Fixed.

**Comment by ameshkov** [comment] 2020-09-13 20:21
As @wanesoft said, there will always the problem with our implementation and the script logic:

> Second. We are closing the connection, but the script needs to save it, so even if the encoding problem is solved, the third page will not load.

We were able to fix the encoding issue, but this issue with closing connection created by GM_xmlhttprequest is quite problematic. @wanesoft what do you think? Also, what's the point of keeping it alive for the script itself?

**Comment by freezewind** [comment] 2020-09-13 20:29
Oh, I able to load the third and more pages, so I think it is fixed in the least nightly.

**Comment by wanesoft** [comment] 2020-09-14 08:06
perhaps the connection is not the main problem. I'll check it out

**Comment by wanesoft** [comment] 2020-09-16 10:57
after a little research, there is a reason for the button disappearing: the script removes all child elements of `<body>` (line number 5475 `$('body > *:not("#container, .readerbtn, .noRemove, #reader_preferences, #uil_blocker,iframe[name=\'mynovelreader-iframe\']")').remove();`), except a small list of elements. so, and we put the styles needed for the script in this place (that's normally) also. and... it's gone

**Closed** 2021-08-10 09:14 UTC
Labels: bug, P4: Low, Windows, Resolution: Fixed, Status: Resolved
