### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR on byruthub.org 

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/CoreLibs#1912] opened 2024-09-06 13:59 UTC
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue URL (Incorrect Blocking)
 [https://byruthub.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fbyruthub.org%2F)
### Comment
> Сайт не открывается при включенном блокировщике, но иногда может и открываться, потом снова нет.

### Screenshots
<details>
  <summary>Screenshot 1 </summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/ld1vq496srkg8wkc4ocs0404s004kgo3jpdmh4yik8.png?nc=1)
</details>
<details>
  <summary>Screenshot 1 with AdGuard disabled</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/kzce40hia804wg0soo88ccsss0wggo023oawa1k05o.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Windows v7.18.1 (4778)
System version: | Microsoft Windows NT 10.0.26100.0
Browser: | Яндекс Браузер
License type: | free
AdGuard driver: | TDI
Tracking protection: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/windows/filters/15.txt`, `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>IndianList
Browsing Security: | enabled
Browsing Security statistics: | disabled
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Userstyles: | disabled

### Import issue configuration (AdGuard for Windows)
[Import](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=adguard%3Aimport_user_configuration%3Fbrowsing_security.enabled%3Dtrue%26browsing_security.statistics_enabled%3Dfalse%26dns.custom_bootstrap%3D%26dns.custom_fallback%3D%26dns.enabled%3Dtrue%26dns.fallback_mode%3DSystem%26dns.filters%3Dhttps%253A%252F%252Ffilters.adtidy.org%252Fwindows%252Ffilters%252F15.txt%252CUser%2Brules%26dns.filters_enabled%3Dtrue%26dns.servers%3DSystem%26dns.timeout%3D0%26filters%3D1.2.3.253%26license_type%3Dfree%26parental_control.enabled%3Dfalse%26product_type%3DWin%26product_version%3D7.18.1%2B%25284778%2529%26referrer%3D%26stealth.enabled%3Dfalse%26system_version%3DMicrosoft%2BWindows%2BNT%2B10.0.26100.0%26url%3Dhttps%253A%252F%252Fbyruthub.org%252F%26user_agent%3DMozilla%252F5.0%2B%2528Windows%2BNT%2B10.0%253B%2BWin64%253B%2Bx64%2529%2BAppleWebKit%252F537.36%2B%2528KHTML%252C%2Blike%2BGecko%2529%2BChrome%252F126.0.0.0%2BYaBrowser%252F24.7.0.0%2BSafari%252F537.36%26userscripts%3Dhttps%253A%252F%252Fuserscripts.adtidy.org%252Frelease%252Fassistant%252F4.3%252Fassistant.user.js%252Chttps%253A%252F%252Fuserscripts.adtidy.org%252Frelease%252Fadguard-extra%252F1.0%252Fadguard-extra.user.js%252Chttps%253A%252F%252Fuserscripts.adtidy.org%252Frelease%252Fpopup-blocker%252F2.5%252Fpopupblocker.user.js%26utm_campaign%3Dreport%26utm_medium%3Dassistant%26utm_source%3Dwin%26win.wfp%3Dfalse)

**Comment by mark99i** [comment] 2024-10-01 16:21
Такая же проблема на 7.19b2 4818

**Comment by BoreS-ks** [comment] 2024-10-03 10:48
Такая же проблема, но можно просто отключить HTTPS фильтрацию и всё работает.

**Comment by neonfit** [comment] 2024-10-03 11:41
Проявляется только на Яндекс.Браузере. На Chrome все работает штатно.

**Comment by mark99i** [comment] 2024-10-05 19:03
Проявляется на всех сайтах за Cloudflare и только в Яндекс.Браузере

**Comment by sfionov** [comment] 2024-10-09 12:21
В соседней таске описаны [сущность проблемы и воркэраунд](https://github.com/AdguardTeam/CoreLibs/issues/1913#issuecomment-2402070538)

**Comment by sfionov** [comment] 2024-10-09 12:21
Duplicate of #1913

**Closed as completed** 2024-10-12 15:15 UTC
Labels: Bug, Resolution: Duplicate, Status: Closed, Priority: P4
