### ISSUE TITLE
antonioli.eu doesn't load in Safari with AG for macOS

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/CoreLibs#1097] opened 2019-08-28 10:34 UTC
### Steps to reproduce
1. Turn off all filters, Stealth Mode and Extensions
2. go to [antonioli.eu](https://www.antonioli.eu)

### Actual behavior

antonioli.eu doesn't load in Safari, console and filtering log are empty

only HTTPS filtering exclusion helps

### Your environment
* macOS: 10.14.6
* Safari: 12.1.2 (14607.3.9)
* Adguard: 2.1.2.595 beta
* CoreLibs: 1.4.138

**Comment by seba2282** [comment] 2019-08-28 10:56
I see new beta. Try first update Adguard extension for safari. 
https://adguard.com/en/article/adblock-adguard-safari.html

**Comment by ameshkov** [comment] 2019-08-28 11:30
Duplicate of #674

**Closed by ameshkov** 2019-08-28 11:30 UTC
