### ISSUE TITLE
YouTube video uploading doesn't works when quic/gquic is being blocked by Adguard.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1596] opened 2022-02-22 11:15 UTC
@paleparanoid commented on [Wed Feb 09 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106)

### Issue Details

- **AdGuard version:**
  -  v4.0 Nightly 32 (73) - but version doesn't matter here, Adguard block completely all quic/gquic connections on all versions.
- **Filtering mode:**
  -  Local VPN
- **Device:**
  - Redmi Note 9s
- **Operating system and version:**
  Android 10.
- **Root access:**
  - No.

### Expected Behavior

I wanted to upload video to YouTube via official YouTube app. Often I uploaded video via PC, but this time I have to use phone for it. It should just upload this video.

### Actual Behavior

But It haven't. The uploading stopped on Preparing. As you can see, Adguard only blocks some gquic connections. If you disable protection in Adguard, everything will upload fine.

### Screenshots

![Screenshot_2022-02-09-09-36-55-267_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/86261854/153135704-e1087046-a138-400f-9156-d6bc4fc33b86.jpg)![Screenshot_2022-02-09-09-37-01-893_com.adguard.android.jpg](https://user-images.githubusercontent.com/86261854/153135713-1c6cf85a-11c9-416b-ba3e-09ee065e3092.jpg)

### Additional Information

 You should stop blocking QUIC and GQUIC for YouTube app (also YouTube Vanced and other mods on it). It's unrealistically to unblock all (g)quic connections, every time addresses are different. 
I completely don't understand why you decided to block all QUIC and GQUIC connections. This is a very stupid decision.

---

@sfionov commented on [Wed Feb 09 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106#issuecomment-1033521789)

Adguard blocks fallbackable protocols that can't filter, to not to bypass ads and tracking. But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI. Looks like a bug, we'll look into it.

As a workaround you may add `com.google.android.youtube` into `pref.quic.bypass.packages` advanced setting.

---

@paleparanoid commented on [Wed Feb 09 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106#issuecomment-1033672033)

> Adguard blocks fallbackable protocols that can't filter, to not to bypass ads and tracking. But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI. Looks like a bug, we'll look into it.
> 
> As a workaround you may add `com.google.android.youtube` into `pref.quic.bypass.packages` advanced setting.

Thanks, i'll try

---

@TPS commented on [Sat Feb 12 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106#issuecomment-1037238174)

> But IETF QUIC is not on this list - AG for Android should bypass it and filter by SNI.

@sfionov You _do_ mean this that just started appearing since the last updates?
![Pngpro_out_48cd796552286db12739fa73667c8382.png](https://user-images.githubusercontent.com/185902/153714954-c7205521-7358-4e5a-a59c-754164e3d942.png)

---

@sfionov commented on [Sat Feb 12 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106#issuecomment-1037239405)

@TPS Not exactly. Before AG 3.6, Adguard always blocked any quic.
If 3.6, "quic://" definition was split into connections gquic:// and quic:// urls. gquic:// connections are still blocked but quic:// connections should work in non-browsers. For some reason they doesn't work in Youtube, and it fallbacks to gquic. That's the problem.

---

@TPS commented on [Sun Feb 13 2022](https://github.com/AdguardTeam/AdguardForAndroid/issues/4106#issuecomment-1037242055)

You must be seeing different logs than me, since I'm only seeing AG's UI log.  But, based on that, that's _not_ the (official app) YT behavior I see.  Just like @paleparanoid's screenshot above, I see YT choosing between, not falling back to, `QUIC` & `gQUIC`.  [I'm aware they're different](https://github.com/AdguardTeam/CoreLibs/issues/487#issuecomment-421626461) & have separate issues dealing w/ their decoding/filtering.  What progress is there on `gQUIC`?

**Comment by sfionov** [comment] 2022-02-25 17:58
@paleparanoid Hello! I can't reproduce this issue - it is uploaded using QUIC without issues.

Can you please tell if your video is long or short?

Also, can you please collect debug logs?

There are steps to reach dev team with debug logs:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced

**Comment by paleparanoid** [comment] 2022-02-25 18:01
> Can you please tell if your video is long or short?

~30 secs
Also, I can't attach any logs now. Phone is ruined. I'm sorry...

**Comment by sfionov** [comment] 2022-11-15 07:52
Closing this for now, reopen if needed.

**Closed by sfionov** 2022-11-15 07:52 UTC
Labels: bug, Version: CoreLibs v1.11
