### ISSUE TITLE
HTML parser issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1222] opened 2019-12-18 14:45 UTC
On some websites, AG fails to parse HTML properly.

* [x] [phimmedia.tv](https://github.com/AdguardTeam/CoreLibs/issues/965)
* [x] [my.gobluefire.com](https://github.com/AdguardTeam/CoreLibs/issues/1288)

**Comment by AdamWr** [comment] 2020-02-04 15:50
It seems that there is similar issue on this website - [http://www.turizmdosyasi.com/index.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.turizmdosyasi.com/index.php)
There is no `local.adguard.org` in source code (happens only on main page).

**Comment by Alex-302** [comment] 2020-02-22 21:02
Another one: `http://lostfilm.tv/`
![image](https://user-images.githubusercontent.com/8361299/75099193-751e6300-55c7-11ea-8482-06c05493cc67.png)

**Comment by Alex-302** [comment] 2020-02-27 11:37
probably another one
https://github.com/AdguardTeam/AdguardFilters/issues/50431#issuecomment-591682828
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/75441341-2e818d80-5966-11ea-9039-55162adee3f7.png)

</details>
Sometimes HTML is valid, sometimes - invalid.

**Comment by ameshkov** [comment] 2020-03-09 10:37
`https://lostfilm.tv`
https://uploads.adguard.com/up04_rm0xq_view-sourcehttpslostfilm.tv.png

**Comment by ameshkov** [comment] 2020-04-10 11:15
@vshlobinag take a look at this one as well - https://github.com/AdguardTeam/CoreLibs/issues/1288

**Comment by AdamWr** [comment] 2020-04-22 20:16
Probably another similar issue NSFW - https://github.com/AdguardTeam/AdguardFilters/issues/54218

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80028614-ac38c400-84e5-11ea-883d-e444e9f60829.png)

</details>

Before checking, please disable these rules (from Base filter):
```
@@||xvideos.com/models/$elemhide,jsinject,extension
@@||xvideos.com/channels/$elemhide,jsinject,extension
```

**Comment by sfionov** [comment] 2020-04-22 20:23
@AdamWr This task is about false negatives mainly... For false positives due to retrieving part of page via XHR, it is much easier to add whitelist rules.

**Comment by AdamWr** [comment] 2020-04-22 20:33
I thought that it's correct place, because this issue looks similar to this one - https://github.com/AdguardTeam/CoreLibs/issues/1288

>For false positives due to retrieving part of page via XHR, it is much easier to add whitelist rules.

Ok, but it means that we can't block some ad leftovers or other elements.
Could it be somehow possible to add exception (`$elemhide,jsinject,extension`) only to request with `other` type?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/80030569-ae505200-84e8-11ea-803a-9255315b2f18.png)

</details>

I tried `@@||xvideos.com/models/$other,jsinject,elemhide,extension` but it's also applied to main document.

**Comment by ameshkov** [comment] 2020-04-22 20:35
Hm, I wonder why element hiding rules could've been applied to an "other"-type request in the first place.

**Comment by AdamWr** [comment] 2020-04-29 10:08
Probably another similar issue - https://github.com/AdguardTeam/AdguardFilters/issues/54475

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/80584010-5bf3c180-8a11-11ea-907e-3394a5140776.png)

![image](https://user-images.githubusercontent.com/29142494/80584329-c7d62a00-8a11-11ea-86da-3c8a84ee9ded.png)

</details>

**Comment by ameshkov** [comment] 2020-05-02 20:32
And one more website with nothing injected: https://cdek.ru/

**Comment by wanesoft** [comment] 2020-07-31 13:05
> I thought that it's correct place, because this issue looks similar to this one - #1288
> 
> > For false positives due to retrieving part of page via XHR, it is much easier to add whitelist rules.
> 
> Ok, but it means that we can't block some ad leftovers or other elements.
> Could it be somehow possible to add exception (`$elemhide,jsinject,extension`) only to request with `other` type?
> 
> Screenshot
> I tried `@@||xvideos.com/models/$other,jsinject,elemhide,extension` but it's also applied to main document.

@AdamWr in this case, we have a request type Document+XHR. So script injection is ok. But there is a display issue on the app side which will be fixed soon

**Comment by AdamWr** [comment] 2020-07-31 13:57
Ok :)
By the way, will it be possible to add exception like this `@@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension` so website will be not broken and we will be able to block ad leftovers and cookie notice, or not?

**Comment by ameshkov** [comment] 2020-07-31 14:19
> @@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension so website will be not broken and we will be able to block ad leftovers and cookie notice, or not?

Isn't it already possible? If it's not then it should be, sounds like a good solution

**Comment by AdamWr** [comment] 2020-07-31 14:23
At the moment rule like this is treated as invalid and it seems that also doesn't work.

![image](https://user-images.githubusercontent.com/29142494/89044265-ff72ac00-d349-11ea-87a2-430b7c7a4033.png)

**Comment by ameshkov** [comment] 2020-07-31 14:27
@wanesoft sounds like an okay solution, let's at least allow this type of rules.

**Comment by wanesoft** [comment] 2020-08-03 14:19
> Ok :)
> By the way, will it be possible to add exception like this `@@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension` so website will be not broken and we will be able to block ad leftovers and cookie notice, or not?

@AdamWr thanks. added in core/pull-requests/2032

**Comment by wanesoft** [comment] 2020-08-11 16:00
> On some websites, AG fails to parse HTML properly.
> 
> * [x]  [phimmedia.tv](https://github.com/AdguardTeam/CoreLibs/issues/965)
> * [x]  [my.gobluefire.com](https://github.com/AdguardTeam/CoreLibs/issues/1288)

works fine

**Comment by wanesoft** [comment] 2020-08-11 16:13
> It seems that there is similar issue on this website - [http://www.turizmdosyasi.com/index.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.turizmdosyasi.com/index.php)
> There is no `local.adguard.org` in source code (happens only on main page).

@AdamWr here is:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/42610583/89921398-51e38080-dc06-11ea-9dba-a0480acd3d2d.png">
can u check it again?

**Comment by AdamWr** [comment] 2020-08-11 16:39
> > It seems that there is similar issue on this website - [http://www.turizmdosyasi.com/index.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.turizmdosyasi.com/index.php)
> > There is no `local.adguard.org` in source code (happens only on main page).
> 
> @AdamWr here is:
> <img alt="image" width="335" src="https://user-images.githubusercontent.com/42610583/89921398-51e38080-dc06-11ea-9dba-a0480acd3d2d.png">
> can u check it again?

It seems that it works fine now and I can't reproduce this issue anymore.

**Comment by wanesoft** [comment] 2020-08-12 08:11
> lostfilm.tv

works fine

**Comment by wanesoft** [comment] 2020-08-12 08:46
> probably another one
> [AdguardTeam/AdguardFilters#50431 (comment)](https://github.com/AdguardTeam/AdguardFilters/issues/50431#issuecomment-591682828)
> https://docviewer.yandex.ru/
> Load any document to yandex disk and open it.
> 
> Sometimes HTML is valid, sometimes - invalid.

I cannot explain this behavior, but if you turn off AdGuard, then nothing will change. and only Chrome do that

**Closed** 2020-08-12 08:50 UTC
Labels: P3: Medium, bug

**Comment by AdamWr** [comment] 2020-09-08 20:14
Regarding - https://github.com/AdguardTeam/CoreLibs/issues/1222#issuecomment-667133142
>By the way, will it be possible to add exception like this `@@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension` so website will be not broken and we will be able to block ad leftovers and cookie notice, or not?

Now it's possible to add rule like this, but it's also applied to requests with document type only. Is it how it should works?
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/92523002-e77f2980-f21f-11ea-9a70-7acc626b8866.png)

</details>

Rules:
```
@@||xvideos.com/models/$elemhide,jsinject,extension,badfilter
@@||xvideos.com/models/$xmlhttprequest,jsinject,elemhide,extension
```
Link NSFW - `https://www.xvideos.com/models/jessica-koks`

**Comment by Alex-302** [comment] 2020-09-08 21:25
Also `$$` are not working if added exclusion with `$elemhide,jsinject,extension` (three only, works with any two)

**Comment by ameshkov** [comment] 2020-09-09 07:55
Please open a new issue, this one is closed

**Comment by AdamWr** [comment] 2020-09-09 08:15
>Please open a new issue, this one is closed

Done:
https://github.com/AdguardTeam/CoreLibs/issues/1336
https://github.com/AdguardTeam/CoreLibs/issues/1337
