### ISSUE TITLE
DuckDuckGo/Youtube settings Auto reset

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1021] opened 2019-07-12 10:49 UTC
@Chinaski1 commented on [Mon Jul 01 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2795)

### Steps to reproduce

1. Reset AdGuard settings to default.
2. Turn on Stealth Mode.
3. Turn off every module in Stealth Mode.
4. Delete all cookies and caches in the browser.
5. Visit Youtube and change settings (Dark Mode, Languages, Locations).
6. Wait a few hours and visit Youtube again.

### Customer ID 

[Forum](https://forum.adguard.com/index.php?threads/duckduckgo-youtube.32736/)
**Logs in NCloud**

### Your environment

* Environment name and version: AdGuard 7.1.2817
* Operating system and version: Windows 10.0.18362.0

**Comment by ameshkov** [comment] 2019-07-14 19:36
@sfionov I thought we've already fixed this

**Comment by sfionov** [comment] 2019-07-14 20:11
@ameshkov Yes, fixed in 7.1 release, but one user reported on forum that he reproduced it once on 7.1 release.

I assume that "bug" was actually caused by cookies set before upgrade.

**Closed** 2019-08-07 13:06 UTC
Labels: Check with CoreLibs, P2: High, stealth mode
