### ISSUE TITLE
$redirect modifier for basic rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#128] opened 2017-11-30 14:18 UTC
Discussion:
https://github.com/AdguardTeam/AdguardForWindows/issues/1501

**Comment by ilvjyw** [comment] 2018-07-31 15:27
I've been waiting for a long time
When can it be achieved?

**Comment by sfionov** [comment] 2019-07-22 15:32
Closing as duplicate of #1043 which is more informative

**Closed by sfionov** 2019-07-22 15:32 UTC
Labels: Filtering Engine, feature request
