### ISSUE TITLE
app.print.avery.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1307] opened 2020-06-10 11:51 UTC
@adguard-bot commented on [Mon Jun 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57028)

### Issue URL (Incorrect Blocking)
 [https://app.print.avery.com/dpo8/app/target;name=US_en;ep=USP/customize;project=4736f51555eb18596e85a1ea247c0d26/ctx;bu=https%3A%2F%2Fwww.avery.com%2Fmyaccount%2Fprojects;consumer=Avery/view?customize](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fapp.print.avery.com%2Fdpo8%2Fapp%2Ftarget%3Bname%3DUS_en%3Bep%3DUSP%2Fcustomize%3Bproject%3D4736f51555eb18596e85a1ea247c0d26%2Fctx%3Bbu%3Dhttps%253A%252F%252Fwww.avery.com%252Fmyaccount%252Fprojects%3Bconsumer%3DAvery%2Fview%3Fcustomize)
### Comment
Username: @perfectworld90
> When Adguard is enabled, Avery Address Label project won't open. It would show a complete blank webpage. When Adguard is disabled, problem is solved. 
> --
> The information below is automatically generated. Do not delete it.
> 
> Referrer:
> https://www.avery.com/myaccount/projects
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/JnX8Nzp.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/5uauVOB.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.4.2
Browser: | Chrome
AdGuard driver: | WFP
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/> EasyList China

**Comment by AdamWr** [comment] 2020-06-10 11:54
It seems that it happens usually on first visit.
Before checking it, please disable this rule (from Base filter):
`@@||app.print.avery.com^$elemhide,jsinject,extension`

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/84264437-7bf2c680-ab21-11ea-9fd0-f524c8fd0873.png)

</details>

**Comment by ameshkov** [comment] 2020-06-10 11:56
I am almost sure that the issue is caused by injecting <style> tags

@sfionov should be fixed in the content script

**Closed** 2021-08-10 09:14 UTC
Labels: Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.8
