### ISSUE TITLE
itv.rt.ru - site it not working with enabled protection

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1250] opened 2020-01-23 19:42 UTC
@adguard-bot commented on [Mon Jan 20 2020](https://github.com/AdguardTeam/AdguardFilters/issues/48219)

### Issue URL (Incorrect Blocking)
[https://itv.rt.ru/channels/142773698](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fitv.rt.ru%2Fchannels%2F142773698)
### Comment
Username: @huhen
> Выключение в настройках "Антибанер", "Антитрекинг", "Антифишинг", "Расширения" либо добавление пользовательского правила "@@//itv.rt.ru^$document" не решает проблему.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/RbLdTNE.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/L21P5HJ.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Win
AdGuard version: | 7.3
Browser: | Chrome
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Disable cache for third-party requests, Block WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard French, <br/>EasyList China
Other extensions used: | нету

**Comment by sfionov** [comment] 2020-01-23 19:44
Duplicate of #1248

**Closed** 2020-01-23 19:44 UTC
Labels: bug
