### ISSUE TITLE
"Report the website" doesn't work in Assistant

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#680] opened 2019-01-22 14:58 UTC
@aspasskaya commented on [Tue Jan 22 2019](https://github.com/AdguardTeam/AdguardForMac/issues/408)

### Steps to reproduce
1. Go to Assistant
2. Tap on "Report the website" 

### Expected behavior
https://reports.adguard.com/ru/new_issue.html?product_type=Mac ...

### Actual behavior
Nothing happens

---
* AdGuard nightly 2.0.0.500
* Chrome 71.0.3578.80
* Mac Mojave

**Comment by sfionov** [comment] 2019-01-22 19:08
Duplicate of #595

**Comment by sfionov** [comment] 2019-02-04 12:11
Empty "referrer" field is not error, also User-Agent is needed for UI.

**Comment by szolin** [comment] 2019-02-06 12:16
/core/pull-requests/1020

**Closed** 2019-06-19 15:23 UTC
Labels: Mac, P3: Medium, Userscripts, Windows, bug
