### ISSUE TITLE
URL blocking is not working properly

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#730] opened 2019-02-15 22:03 UTC
Steps to reproduce:
1) Enable Social Media Filter
2) Go to http://progorodsamara.ru/news/view/207467

Actual behavior:
Social widget is not blocked
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/52886758-06b9f000-317e-11e9-9ace-129b9ac60b2c.png)

![image](https://user-images.githubusercontent.com/8361299/52886774-1cc7b080-317e-11e9-86a0-e7825ade6d7b.png)

</details>

The same with Android version with CL.

**Comment by Alex-302** [comment] 2019-03-21 14:22
Another example - cannot block VK comments
https://mister-robot.tv/1-sezon/15-6-seriya.html
![image](https://user-images.githubusercontent.com/8361299/54758787-827fe000-4bf5-11e9-922e-9fc11097a16a.png)
`||vk.com/widget_comments.php$important`

**Comment by ameshkov** [comment] 2019-03-21 14:44
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/771

**Closed by ameshkov** 2019-03-21 14:44 UTC
Labels: Android, Check with CoreLibs, P3: Medium, bug
