### ISSUE TITLE
$popup rule blocks iframe

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1039] opened 2019-07-18 14:07 UTC
Actual behavior with Liste AR:
![image](https://user-images.githubusercontent.com/8361299/61464019-3b74e200-a97e-11e9-8e78-db34519a1c41.png)

Original issue:
https://github.com/AdguardTeam/AdguardFilters/issues/35459#issuecomment-512780152

Please disable this rule in Liste AR(added on our side) before checking:
`@@||drive.google.com/file/$domain=aflamyz.com`

**Comment by sfionov** [comment] 2019-07-19 11:09
Duplicate of #682

**Comment by ameshkov** [comment] 2019-07-19 11:09
No it's not

**Comment by ameshkov** [comment] 2019-07-19 11:10
This one is about HTML parser

**Comment by vshlobinag** [comment] 2019-07-23 13:25
core/pull-requests/1402/

**Closed** 2019-08-07 13:06 UTC
Labels: Filtering Engine, P2: High, bug
