### ISSUE TITLE
www.johnnys.nl

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1449] opened 2021-05-11 10:29 UTC
@adguard-bot commented on [Mon May 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/82890)

### Issue URL (Incorrect Blocking)
 [https://www.johnnys.nl/c/28/actie](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.johnnys.nl%2Fc%2F28%2Factie)
### Comment
Username: @werring
> Problem exists for the entire website. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/OfuleZq.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/A5S4Dh7.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.3.955 release
Browser: | Firefox
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Dutch
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Referrer: | [https://www.johnnys.nl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.johnnys.nl%2F)
Other extensions used: | none

**Comment by Alex-302** [comment] 2021-05-11 10:31
Only HTTPS filtering disabling helps.

**Comment by sxgunchenko** [comment] 2021-05-12 13:21
I'm able to reproduce it with version 1.7, but it seems to be fixed in 1.8

**Closed** 2021-08-10 09:13 UTC
Labels: bug, Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.8, Low
