### ISSUE TITLE
www.adorama.com is broken by filtering

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1548] opened 2021-11-09 17:44 UTC
@adguard-bot commented on [Fri Oct 29 2021](https://github.com/AdguardTeam/AdguardFilters/issues/98455)

### Issue URL (Incorrect Blocking)
 [https://www.adorama.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.adorama.com)
### Comment
> when AdGuard is on, www.adorama.com does not load or fails to respond. When ADGuard is off, www.adorama.com works normally.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AMbiWIl.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/wTmaRGe.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.6.1.1051 release
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | disabled
Other extensions used: | none

**Comment by Alex-302** [comment] 2021-11-09 17:45
Broken even with these settings
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/140976776-1358da8b-aa05-4eb0-84a2-7c0dd23e55c5.png)

</details>

**Comment by AdamWr** [comment] 2021-11-09 18:06
Looks similar to this issue - https://github.com/AdguardTeam/CoreLibs/issues/1518

**Comment by ameshkov** [comment] 2021-11-11 11:22
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/1518

**Closed by ameshkov** 2021-11-11 11:22 UTC
Labels: bug
