### ISSUE TITLE
Why Has The development of the macOS App Stopped?

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/CoreLibs#1788] opened 2023-07-28 19:44 UTC
Why has the development of the macOS Adguard system app being ignored?

There have been NO substantial improvements for quite a long time.

The development of Adguard macOS app has seemingly stagnated.

The development of the macOS app NOT been updated to provide features which are equal to or better than the Extension.

I fully acknowledge the macOS system app is far more technically capable than any Extension.

So why is the macOS app user interface is lacking features that the Extension contains and why is the macOS app is so very badly designed and that it is need of a major overhaul.

The Technical Issue of the Filtering Logs NOT recording Cosmetic/Custom User Rules has been known by Adguard for at least 5 years and they done absolutely NOTHING to fix this.

The folks at Adguard seem to have NO INTEREST in fixing this.

The fact is that a Filtering Log which is incompetent and lacks features creates issues when items on a webpage are blocked and you have NO RECORDS TO SHOW WHAT COSMETIC ITEMS ARE BLOCKED, This makes it a very difficult and time consuming task to find out what is blocking parts of a webpage.

People whom are paying for a License to use a paid product deserve much better.

It is absolutely disgusting and abhorrent that the staff at Adguard have been so very, very, lazy that they can not be bothered improving their paid for Adguard and introducing what it sorely lacks and bringing this product up to its full potential.

Adguard is not improving, development has seeming ground to a halt and the problem with the Filtering Log has been present for 5 very long years now.

The customers of Adguard are paying hard earned cash for this product and in return we get a very badly designed product.

Paying customers deserve much better treatment, this is simply not good enough

**Comment by sfionov** [comment] 2023-07-28 19:46
Duplicate of #180

**Closed by sfionov** 2023-07-28 19:46 UTC
Labels: Priority: P4
