### ISSUE TITLE
High CPU Load Adguard Firefox Windscribe Browserplugin

### ISSUE THREAD

**Issue by Glassertje** [AdguardTeam/CoreLibs#961] opened 2019-06-07 16:24 UTC
If you login the Windscribe browserplugin in Firefox Adguard CPU is high. If necessary you can use my login to fix the issue.

**Comment by ameshkov** [comment] 2019-06-07 16:25
Duplicates #960

**Comment by sfionov** [comment] 2019-06-07 16:26
Duplicate of #960

**Closed by ameshkov** 2019-06-07 16:25 UTC
Labels: duplicate
