### ISSUE TITLE
Network performance with a 10Gbps network

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#1470] opened 2021-06-29 15:08 UTC
Here's the original report:
https://github.com/AdguardTeam/AdguardForMac/issues/883

Things to check:
1. CoreLibs performance. We did this not too long ago, probably it's time to do it again.
2. Could it be a NetworkExtension limitation? IMO, it makes sense to check it without NE, is there a simple way to somehow "proxify" iperf traffic?

**Comment by ngorskikh** [comment] 2021-06-29 15:17
Considering that we shouldn't be proxying `iperf3` in the first place (unless the user intentionally added it to filtered apps), this is most probably caused by interaction between iperf and the network extension framework. We need to reproduce this though, before jumping to any conclusions :)

**Comment by kdeldycke** [comment] 2021-06-30 06:43
Hi @ngorskikh and thanks @ameshkov for the bug triage.

I'm available for any troubleshooting and tests! :)

**Comment by ngorskikh** [comment] 2021-06-30 13:10
@kdeldycke Hi! That's great, because I wasn't able to reproduce this on my own :harold: Do you have `iperf3` in AdGuard's filtered apps (which is unlikely, but still)? Is it `iperf3` from homebrew or some other source? I've also noticed that the two iperf runs that you mentioned in the original issue are from different machines, maybe there's something else different between those runs, besides AdGuard being on/off?

**Comment by kdeldycke** [comment] 2021-07-19 14:03
Thanks @ngorskikh for the answer, and sorry for the delay... 🙇

I tried to reproduce the issue but to no avail. I think what likely happened is that I had connectivity issues or resource exhaustion and the ethernet connection deactivated. The reduced bandwidth was probably the Wifi fallback.

Anyway, let's close this issue for now. I'll add more details if something similar happens.

**Closed** 2021-07-28 20:04 UTC
Labels: Resolution: Cannot Reproduce, Status: Resolved, bug

**Comment by kdeldycke** [comment] 2022-04-18 17:30
FTR, there was an limitation of network performances that was fixed in https://github.com/AdguardTeam/CoreLibs/issues/1561
