### ISSUE TITLE
HTTPS filtering is not applied to slivy.news

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1559] opened 2021-12-03 16:53 UTC
@adguard-bot commented on [Thu Nov 25 2021](https://github.com/AdguardTeam/AdguardFilters/issues/101226)

### Issue URL (Annoyance)
 [https://slivy.news/es-bez-mozgov/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fslivy.news%2Fes-bez-mozgov%2F)
### Comment
Username: @zubrRB
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/OcXShME.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.7.2
Browser: | Chrome
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (1), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your Referrer from third-parties (example.com), <br>Hide your User-Agent (), <br>Hide your IP address ()
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js,<br>https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js,<br>https://greasyfork.org/scripts/14085-kinozal-tv-magnet-links/code/kinozaltv%20magnet%20links.user.js,<br>https://github.com/Owyn/HandyImage/raw/master/HandyImage.user.js,<br>https://greasyfork.org/scripts/394820-mouseover-popup-image-viewer/code/Mouseover%20Popup%20Image%20Viewer.user.js,<br>https://download.sf-helper.com/chrome/helper.user.js
Referrer: | [https://slivy.news/a-sudi-kto/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fslivy.news%2Fa-sudi-kto%2F)

**Comment by zubrRB** [comment] 2021-12-03 16:58
Duplicate of #1508

**Comment by sfionov** [comment] 2021-12-03 17:09
Will be fixed in the upcoming CoreLibs v1.9

**Closed** 2021-12-03 17:08 UTC
Labels: bug, question
