### ISSUE TITLE
mfah.org does not open

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1634] opened 2022-05-09 16:18 UTC
@adguard-bot commented on [Mon May 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/118111)

### Issue URL (Incorrect Blocking)
 [https://www.mfah.org/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.mfah.org%2F)
### Comment
Username: @robertcope
> Both Chrome and Safari fail. curl works fine.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/JJxHWjY.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/qtmXOCO.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.8.1.1140 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `NextDNS`<br>filters: `Adguard DNS filter (also used locally)`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>Legitimate URL Shortener<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | AdGuard Extra
Other extensions used: | The only other extension that could have any interaction is Bitwarden.

**Comment by Alex-302** [comment] 2022-05-09 16:21
Reproduced on Macos only(`.1141 nightly (CL-1.9.62, DNS-1.7.22)`)
[adg.zip](https://github.com/AdguardTeam/CoreLibs/files/8653459/adg.zip)
Site opens if HTTPS filtering disabled only.

**Comment by zzebrum** [comment] 2022-05-13 12:38
@Alex-302 macOS version? It seems to be working ok on my side, I'm on release .1140 which is basically the same version as yours.

**Comment by Alex-302** [comment] 2022-05-13 12:40
`12.3.1 (21E258)`
Also not reproduced at the moment.

@robertcope Could you please check again?

**Comment by zubrRB** [comment] 2022-05-13 13:18
`Protect from DPI` https://github.com/AdguardTeam/CoreLibs/issues/1615

**Comment by sfionov** [comment] 2022-05-13 13:26
@zubrRB Works for me even with this option enabled

**Comment by robertcope** [comment] 2022-05-13 13:31
Howdy, indeed it does seem to be working now. Unclear what changed... I
know a new version of Chrome has been released in the meantime. Thanks for
following up!

robert

**Comment by zubrRB** [comment] 2022-05-13 13:36
@sfionov У меня первоначально в AG для Windows с включенной опцией `ERR_CONNECTION_CLOSED` и по `...SSL`. 
После нескольких перезагрузок страницы начинает некоторое время снова открываться... до следующего раза.

**Comment by grumaxxx** [comment] 2022-06-03 09:08
@robertcope Do you still have a problem? If site still falling for you, can you, plese send logs ([how to make this](https://kb.adguard.com/en/windows/solving-problems/adguard-logs)). Issue doesn't reproduced for me with different settings on Mac/Win/Android.

**Comment by robertcope** [comment] 2022-06-03 10:07
I narrowed it down to the "Protect from DPI" option in Stealth
Mode->Miscellaneous. I thought this ticket had indicated that the problem
had been narrowed down to that. I will try and get some logs for you.

**Comment by sfionov** [comment] 2022-06-14 07:56
Thank you, added to list. Closing this in favor of #1645

**Closed** 2022-06-14 07:56 UTC
Labels: bug, SSL, Mac, Resolution: Duplicate, Status: Resolved, Version: CoreLibs v1.10
