### ISSUE TITLE
HTTP/3 and QUIC filtration feature request

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/CoreLibs#1572] opened 2021-12-18 13:14 UTC
Hello,

unfortunately, I could not find any detailed information about the status of HTTP/3 and QUIC filtering support here or on the forum. All I know is that filtration engine are now forcibly downgrading the connection protocol to HTTP/2☹️

So please add the HTTP/3 and QUIC traffic filtering feature in future releases for desktop and mobile applications🙂

Thank you.
Best regards!🎁

**Comment by d0x360** [comment] 2021-12-19 06:42
There is DNS quic support if you use Adguard DNS.  I don't think any of the other servers can use it yet.

**Comment by ammnt** [comment] 2021-12-19 07:52
> There is DNS quic support if you use Adguard DNS. I don't think any of the other servers can use it yet.
> 
> A potential issue with http/3 is ports. If DNS uses a different port than other traffic then "they" will know what's a DNS request and what's regular traffic.
> 
> So hopefully they use the same port for both DNS and regular browsing traffic.
> 
> It's still really new though and Adguard can't just add it if the system (Android in this case) doesn't support it... I think.

You don't understand what I'm talking about🤦🏻‍♂️ Read how the HTTP/3, QUIC, and DNS-over-QUIC protocols differ. DoQ servers from AdGuard are the first, but not the only ones in the world for a long time - NextDNS also have support too.

HTTP/3 protocol uses the same port 443 as normal HTTPS. No problem here.

And I'm talking not only about Android, but about all the platforms supported by AdGuard applications.

**Comment by d0x360** [comment] 2021-12-19 08:42
I do understand, I was just pointing something out, and based on the
protocols I've read what I said is correct.

As for Android I probably should been more clear.  "In this case" was just
referring to me because I do... 99.99999% of my web browsing on my phone.
Plus I had just posted 2 issues in the Android section so it was on my mind.

I also know there are more DNS servers that support Quic.  I was just
talking about the default ones that are options in Adguard.

Nice facepalm BTW.. I think someone needs to chill.  Even if I was 101%
wrong about something this isn't Reddit or the Adguard forums it's Github.

If someone gets something wrong you explain it to them without being
condescending.

**Comment by d0x360** [comment] 2021-12-19 08:45
I do understand, I was just pointing something out, and based on the
protocols I've read what I said is correct.

As for Android I probably should been more clear.  "In this case" was just
referring to me because I do... 99.99999% of my web browsing on my phone.
Plus I had just posted 2 issues in the Android section so it was on my mind.

I also know there are more DNS servers that support Quic.  I was just
talking about the default ones that are options in Adguard.

Nice facepalm BTW.. I think someone needs to chill.  Even if I was 101%
wrong about something this isn't Reddit or the Adguard forums it's Github.

If someone gets something wrong you explain it to them without being
condescending.

**Comment by d0x360** [comment] 2021-12-19 08:48
I feel like I walked into a grade school...

You're seriously putting the "I'm insulting you but being sneaky icons" on my post?  lol ok...

**Comment by ameshkov** [comment] 2021-12-20 10:31
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/487

**Closed by ameshkov** 2021-12-20 10:31 UTC
