### ISSUE TITLE
Slow loading of tiles on maps.yandex.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#777] opened 2019-03-06 17:42 UTC
It's rather easy to reproduce, just open it with disabled caching. The first load is very slow. Compare it to what you have with disabled AdGuard.

**Comment by roboderpy** [comment] 2019-03-24 01:23
This is caused by slow HTTP/2 filtering, both on Smartphone and on Desktop (after 7.0 is released)

**Comment by sfionov** [comment] 2019-04-14 03:41
Fixed in CL 1.3.275.

**Closed** 2019-06-19 15:23 UTC
Labels: P2: High, bug
