### ISSUE TITLE
Compatibility issue with Firefox beta and CoreLibs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#864] opened 2019-04-15 18:47 UTC
STR:

1. Install Firefox beta and AG v7 nightly
2. Go to aliexpress.com and try navigating through the website
3. At some point, everything will get stuck

**Comment by sfionov** [comment] 2019-04-25 13:17
Current HTTPS "autodetecting" bypass scheme is not compatible with Firefox 66+ because it doesn't do reconnects. 

According to their bugzilla, they are in process of moving to MITM detection and one allowed "mitmboxes" behaviour - enterprise_roots=true + to filter, no manipulations (like connection resets) at the "mitmboxes" side.

**Comment by aspasskaya** [comment] 2019-06-13 15:45
the problem is still exist
login in aliexpress.com
![image](https://user-images.githubusercontent.com/43952607/59447079-644c0980-8e0b-11e9-9f9c-14451cc42e5a.png)

**Comment by sfionov** [comment] 2019-06-19 13:57
Issue in the last message is aliexpress problem - their return-after-login page is empty HTTP404 page even with AdGuard disabled.

**Closed** 2019-06-19 15:23 UTC
Labels: P2: High, bug, compatibility
