### ISSUE TITLE
Errors in userscripts ("Unexpected end of input..." and "Access to XMLHttpRequest..")

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/CoreLibs#980] opened 2019-06-24 10:50 UTC
STR
* Install one of the following
https://greasyfork.org/en/scripts/15173-visited-lite
https://greasyfork.org/en/scripts/369400-local-youtube-downloader
https://greasyfork.org/en/scripts/368333-rutor-org-seed-graph

* Go to the console and get smth like that https://uploads.adguard.com/buker_eqbg3.png

**Comment by sxgunchenko** [comment] 2019-09-25 08:28
The first userscript triggers the issue in userscript wrapper. If a userscript has comment in the ending line, the wrapper appends closing brackets to that line and it causes those brackets to be commented out.

Cannot reproduce any issues with the latter ones.

**Closed** 2020-01-27 12:24 UTC
Labels: P3: Medium, Userscripts, bug
