### ISSUE TITLE
Crash on filter validating

### ISSUE THREAD

**Issue by northis** [AdguardTeam/CoreLibs#839] opened 2019-04-03 15:00 UTC
`isRuleValid` crashes with empty string

**Comment by sfionov** [comment] 2019-04-03 15:15
Marshaling error - "" marhals as NULL, not IntPtr to (char[]){0}

**Comment by adbuker** [comment] 2019-04-03 15:20
duplicate of https://github.com/AdguardTeam/CoreLibs/issues/815

**Closed by adbuker** 2019-04-03 15:20 UTC
