### ISSUE TITLE
forum.pclab.pl - ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1344] opened 2020-09-20 11:59 UTC
### Steps to reproduce:
1. Go here - [https://forum.pclab.pl/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://forum.pclab.pl/)

### Actual behavior

Website doesn't open.
It looks like similar issue to this one - https://github.com/AdguardTeam/CoreLibs/issues/1340 and it also happens on Android.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/93710587-2d08f400-fb48-11ea-864c-1af496582867.png)

</details>

### Your environment

* AdGuard for Windows 7.5 nightly 28 (build 3390, CL 1.7.108)

**Comment by ameshkov** [comment] 2020-09-21 09:43
Can't reproduce with CL-1.7.98, seems to be a new bug

**Comment by ameshkov** [comment] 2020-09-21 09:44
@sfionov says it's fixed in 1.7.111

**Closed** 2020-09-21 09:44 UTC
Labels: bug
