### ISSUE TITLE
[Android Nightly] Issues with HAR-file

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/CoreLibs#326] opened 2018-06-07 16:07 UTC
Adguard version: 2.12.47

- Can't open .har recorded by Adguard with [Charles](https://www.charlesproxy.com/)

`Charles could not open this file due to the following error: MalformedURL: no protocol: /rtistatus3.dat`

**Comment by Alex-302** [comment] 2018-06-07 19:15
Probably related to https://github.com/AdguardTeam/AdguardFilters/issues/17532#issuecomment-395142125
some responses are not readable(long random URLs, when Yandex detects ad blocking)
![image](https://user-images.githubusercontent.com/8361299/41121123-2c5a2334-6aa0-11e8-82fd-36ef59de012d.png)

**Comment by sxgunchenko** [comment] 2018-06-20 14:07
core/pull-requests/409

**Comment by vozersky** [comment] 2018-07-11 14:09
Charles could not open this file due to the following error: EOF: End of input at line 13235 column 2 path $.log.entries[102]

**Comment by vozersky** [comment] 2018-07-11 14:23
Adguard 2.12.106n

Charles could not open this file due to the following error: EOF: End of input at line 13235 column 2 path $.log.entries[102]

**Comment by szolin** [comment] 2018-07-19 11:04
Closing the issue, as there's not enough information.  We need the steps to reproduce it, logs and the .har file itself.

**Closed by szolin** 2018-07-19 11:04 UTC
Labels: P3: Medium, bug

**Comment by Alex-302** [comment] 2018-07-24 08:57
@sxgunchenko still can't open these requests. Could you please check again?(long URLs with random names, for example url with `fif7KWD8`)
New HAR
http://file.sampo.ru/qtkz2j/

![image](https://user-images.githubusercontent.com/8361299/43127702-c0fb1da6-8f38-11e8-8273-d3e564e20718.png)

**Comment by szolin** [comment] 2018-07-24 10:01
Fiddler can't open this document because of response header:
X-Consumed-Content-Encoding: gzip

Probably, Fiddler treats X-Consumed-Content-Encoding header as Content-Encoding and tries to decode gzip data, but it shouldn't, because this document is a plain text javascript.

P.S. Google Chrome opens this document correctly.

**Comment by Alex-302** [comment] 2018-07-24 10:37
Ok, thanks.
