### ISSUE TITLE
anz.com - HTTPS issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1216] opened 2019-12-10 20:41 UTC
@adguard-bot commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45707)

### Issue URL (Incorrect Blocking)
[https://www.anz.com/INETBANK/bankmain.asp](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.anz.com%2FINETBANK%2Fbankmain.asp)
### Comment
Username: @planet0
> Happens when trying to login to ANZ Banking. Tried to exclude entire anz.com and anz.com.au domains from AdGuard entirely, still doesn't make a difference. Only disabling or quitting AdGuard works. CoreLibs related maybe?

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7yYbQ0a.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/DdPdUMj.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.2.3.661 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (), Block WebRTC, Block Location API
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances
Other extensions used: | None

---

@planet0 commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45707#issuecomment-563976328)

No issues with AdGuard Browser Extension.

---

@Alex-302 commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45707#issuecomment-564098149)

@planet0 please try the latest build
http://agrd.io/mac_nightly

> No issues with AdGuard Browser Extension.

it seems this site is not excluded in HTTPS settings yet in your version.

---

@planet0 commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45707#issuecomment-564215483)

@Alex-302 Unfortunately the nightly build didn't make a difference

Checking the console, it comes up with this error:
`Failed to load resource: net::ERR_CONNECTION_RESET (BANKAWAY:1)`

So when AdGuard is enabled, something is affecting the HTTPS connection, even if added to exclusions.

**Comment by ameshkov** [comment] 2019-12-26 11:05
@planet0 what if you don't exclude these domains from HTTPS filtering, but on the contrary, include them? Does it change anything?

**Comment by planet0** [comment] 2019-12-26 11:09
@ameshkov - woah. Removing `anz.com`, `anz.com.au`, and `anz.co.nz` from the default HTTPS exclusion list works :-)

**Comment by ameshkov** [comment] 2019-12-26 11:11
Yeah, this is definitely that issue then. Most likely it is fixed in the new CL update.

**Comment by ameshkov** [comment] 2020-01-20 11:01
In theory, this bug is already fixed in the latest CL dev version.
@sfionov please re-test it.

**Comment by ngorskikh** [comment] 2020-01-21 14:25
Can't reproduce with CoreLibs proxy (master). The URL in description doesn't match the screenshots, though...

**Comment by ameshkov** [comment] 2020-01-21 14:26
@ngorskikh make sure that HTTPS filtering is disabled for the domain

**Comment by ngorskikh** [comment] 2020-01-21 14:44
@ameshkov re-checked with tls filtering disabled for anz.com, still can't reproduce :)

**Comment by ameshkov** [comment] 2020-01-21 20:21
Well, then it's confirmed that this bug is fixed already.

**Comment by jputting** [comment] 2020-01-21 21:25
For me personally this whole debacle has been going on since Late NOVEMBER 2019.

It is absolutely astonishing and beyond belief that I reported this and repeatedly beg and pleaded for this to be fixed more than 2 months ago as this was affecting a very vital and critically important service.

After more than 2 months we are STILL WAITING FOR THE NEXT UPDATE TO FIX THIS.

You people at Adguard expect people to pay good money for a subscription to your Adguard adblocker and then you subject then to extremely long waiting times for critical issues to be fixed...............................................................

Your customer support is shockingly bad.

**Comment by planet0** [comment] 2020-02-02 09:33
@ngorskikh @ameshkov Although it is resolved the blank page, you do need to remove the anz.com, anz.com.au, and anz.co.nz from the HTTPS Exclusions list to work, otherwise an SSL error occurs.

Once removed, the ANZ website for Internet Banking works perfectly.

<img width="405" alt="Screen Shot 2020-02-02 at 7 53 39 am" src="https://user-images.githubusercontent.com/46271764/73606135-1a629e80-45fb-11ea-99d9-83d943e026ff.png">
<img width="571" alt="Screen Shot 2020-02-02 at 7 53 22 am" src="https://user-images.githubusercontent.com/46271764/73606136-1a629e80-45fb-11ea-972d-27cf59b68085.png">

**Comment by ameshkov** [comment] 2020-02-02 16:06
> otherwise an SSL error occurs.

This one is fixed in the dev build already, and it will soon be pushed to nightly

**Comment by planet0** [comment] 2020-02-02 21:47
@ameshkov Oh, whoops. My mistake, sounds good :)

**Closed** 2020-08-04 10:51 UTC
Labels: P3: Medium, bug
