### ISSUE TITLE
net::ERR_HTTP2_PROTOCOL_ERROR on www.adorama.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1518] opened 2021-09-20 13:19 UTC
@adguard-bot commented on [Tue Sep 07 2021](https://github.com/AdguardTeam/AdguardFilters/issues/94023)

### Issue URL (Incorrect Blocking)
 [https://www.adorama.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.adorama.com)
### Comment
> adorama.com page does not load at all when AdGuard is active

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/tINblOy.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/pkCn1eK.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.6.0.1011 nightly
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>EasyList<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese, <br/>EasyList Italy
Userscripts: | disabled

**Comment by Alex-302** [comment] 2021-09-20 13:20
Also reproduced with nightly builds on Android and Windows.

**Comment by jertonomics** [comment] 2021-12-07 21:41
This is what happened when I reported this a few months back. It was closed and the issue still remains. Please tell us what the issue is and if it's been fixed. Adorama.com is still not loading.

**Comment by BooBerry** [comment] 2021-12-07 21:44
From what I can tell, it was recently fixed in CoreLibs update that update hasn't landed in any of the apps yet. The issue, from what I understand, is related to HTTP/2.

**Comment by ameshkov** [comment] 2021-12-08 07:59
@BooBerry yeah, that's right, CoreLibs v1.9 will land in the AG for Mac v2.8 and AG for Win v7.9 (first nightlies of them are planned for the next week).

The versions which are currently in public testing both use CL v1.8.

**Closed** 2021-12-29 15:18 UTC
Labels: bug, compatibility, Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.9

**Comment by BooBerry** [comment] 2022-01-03 10:34
Loading adorama.com was fixed in AG for Windows 7.9 nightly 2, but because of the issue with sites not loading it looks like this fix (and others from CoreLibs 1.9) was reverted with 7.9 nightly 3, so adorama.com doesn't load again. So as of right now, it's not resolved again.
