### ISSUE TITLE
Why Is The macOS Adguard So Badly Designed?

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/CoreLibs#1787] opened 2023-07-26 12:54 UTC
As a fully paid personal lifetime user of the Adguard macOS app I am personally disgusted that the Adguard macOS app lacks features found in the 100% free Extension.

The Adguard macOS app has not got these features:

1. No recording of Cosmetic/Custom Rules which have Blocked things on webpages in the Filtering Log.

2. The overall design of the macOS app Filter Log is quite bad, the colours used to designate various Rules are poorly chosen. The Extension Filter Log is much more user friendly and does indeed record blocked cosmetic elements or items blocked via Cosmetic/User Custom Rules

2. No count of Total Number of Filter Rules in individual Filter Lists or a Total Number of All Filter Rules

3. No option to use Optimized Filter Lists.

Why has the development of the macOS app NOT been updated to provide features which are equal to or better than the Extension.

I fully acknowledge the macOS system app is far more technically capable than any Extension.

So why is the macOS app user interface is lacking features that the Extension contains and why is the macOS app is so very badly designed and that it is need of a major overhaul.

The Technical Issue of the Filtering Logs NOT recording Cosmetic/Custom User Rules has been known by Adguard for at least 5 years and they done absolutely NOTHING to fix this.

The folks at Adguard seem to have NO INTEREST in fixing this.

The fact is that a Filtering Log which is incompetent and lacks features creates issues when items on a webpage are blocked and you have NO RECORDS TO SHOW WHAT COSMETIC ITEMS ARE BLOCKED, This makes it a very difficult and time consuming task to find out what is blocking parts of a webpage.

People whom are paying for a License to use a paid product deserve much better.

The customers of Adguard are paying hard earned cash for this product and in return we get a very badly designed product, which Adguard is not improving, the problem with the Filtering Log has been present for 5 very long years now.

AFTER 5 YEARS THERE IS STILL NO ACTION TAKEN BY ADGUARD TO FIX THIS AT ALL.

Some features may indeed may be more difficult to implement in a macOS app.

But Adguard  spent a lot of time and effort developing the Manifest V3 Extension which was very difficult and time consuming to develop due to the restrictions of Manifest V3.

Adguard gets ABSLOUTELY NO REVENUE/INCOME FROM A FREE EXTENSION.

Yet they gave this FREE EXTENSION priority treatment and left the paid for macOS app languish and it still sorely lacks features that it needs. 

Adguard depends on revenue from customers whom pay for a license to use the full system macOS app and yet Adguard ignores what their paying customers want by still refusing to introduce improvements to the Filtering Log after 5 very long years and there is still no indication that Adguard is ever going to improve and develop their macOS app.

What type of business model do they run, when they offend paying customers of the macOS app by dragging their heels and not introducing much needed features 

But instead of spending time and research on development of the macOS app
Adguard is taking paying customers for granted and allowing the development of the macOS app to languish and they can't even be bothered giving their paid customers a full featured top quality app.

**Comment by sfionov** [comment] 2023-07-28 19:46
Duplicate of #180

**Closed by sfionov** 2023-07-28 19:46 UTC
Labels: Priority: P4
