### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#594] opened 2018-11-06 11:27 UTC
@adguard-bot commented on [Tue Oct 30 2018](https://github.com/AdguardTeam/AdguardFilters/issues/24600)

### Issue URL (Incorrect Blocking)
[https://www.apkmirror.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.apkmirror.com)
### Comment
Username: @djdelarosa25
> I cannot upload APKs on APKMirror when AdGuard is enabled. The progress bar would complete rapidly (my upload speed isn't fast at all) but an error would show (as shown in one of the screenshots). I tried disabling DNS filtering but the issue would persist. Disabling AdGuard entirely would alleviate the problem. The progress bar would finish noticeably slower, more reflective of my current upload speeds, and the process would complete without any error.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/kBBhT4Z.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/fxQCF3J.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.247
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media

**Comment by ameshkov** [comment] 2018-11-06 11:37
Most likely this is a duplicate of #542

**Closed by ameshkov** 2018-11-06 11:37 UTC
