### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR on some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1374] opened 2020-11-17 20:53 UTC
After updating Chrome to the latest stable version 87.0.4280.66 I noticed that sometimes websites load endlessly and there is `ERR_HTTP2_PROTOCOL_ERROR` in the console.
It happens sometimes and it's rather not easy to reproduce, but for example it happens on (if it happens then usually on the first visit) - https://translate.google.com/

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/99445498-e6543200-291d-11eb-8238-a9ff3f291d1b.png)

</details>

I'm not sure if it's related to AdGuard, but without AdGuard I couldn't reproduce it.

Probably related - https://forum.adguard.com/index.php?threads/adguard-started-to-slow-chrome-down-recently.40593/#post-204916

**Comment by ameshkov** [comment] 2020-11-17 21:27
WFP driver + default (not redirect) filtering mode, right?

**Comment by AdamWr** [comment] 2020-11-17 21:33
WFP driver + redirect driver mode, but I also checked it with default filtering mode and I had the same issue.

**Comment by ameshkov** [comment] 2020-11-17 22:19
I've been able to reproduce it once, but since the browser restart, I cannot do that anymore.

Is there any stable way to repro?

**Comment by HenryQW** [comment] 2020-11-17 22:38
@ameshkov 

I find that using chrome's address bar to perform a google search has a very high chance of triggering this issue. Chrome will append some query parameters in the URL.

`https://www.google.com/search?q=adguard&oq=adguard&aqs=chrome..69i57j69i59l2j69i60l5.2023j0j9&sourceid=chrome&ie=UTF-8`

**Comment by ameshkov** [comment] 2020-11-17 22:43
Since I cannot reproduce this anymore, here's an instruction for anyone who's able to do this and willing to help.

1. Start with an empty browser, don't go anywhere, don't sign in anywhere.
2. Open chrome://net-export, click "Start logging to disk", it will let you choose a target file
3. Enable "debug-level" logs in AdGuard.
    * Mac: menu -> advanced -> logging level -> debug
    * Windows: tray menu -> advanced -> logging level -> debug
4. Reproduce the issue
5. **Write down the problematic page URL**
6. Stop logging in chrome://net-export
7. Export logs in AdGuard
    * Mac: menu -> advanced -> export logs and system info
    * Windows: tray menu -> advanced -> export logs and system info
8. Archive both files (logs and chrome-net-export)
9. Send them to `devteam@adguard.com`. Mention this issue there, and also tell us the exact URL of the page that failed to load.

**Comment by HenryQW** [comment] 2020-11-17 22:48
@ameshkov I wish I can help out here but I'm hitting multiple deadlines myself.

I have [opened an issue](https://github.com/AdguardTeam/AdguardForMac/issues/779), [uploaded a video](https://youtu.be/sP4VdX2qwbc), and also wrote a post [on the forum](https://forum.adguard.com/index.php?threads/adguard-started-to-slow-chrome-down-recently.40593/). Debug level logs were sent to apple@adguard.com.

**Comment by ameshkov** [comment] 2020-11-17 22:56
@HenryQW no worries and thank you for your help! We'll try to find out what's causing it asap.

**Comment by WorldIRC** [comment] 2020-11-17 23:03
> Since I cannot reproduce this anymore, here's an instruction for anyone who's able to do this and willing to help.
> 
> 1. Start with an empty browser, don't go anywhere, don't sign in anywhere.
> 2. Open chrome://net-export, click "Start logging to disk", it will let you choose a target file
> 3. Enable "debug-level" logs in AdGuard.
>    
>    * Mac: menu -> advanced -> logging level -> debug
>    * Windows: tray menu -> advanced -> logging level -> debug
> 4. Reproduce the issue
> 5. **Write down the problematic page URL**
> 6. Stop logging in chrome://net-export
> 7. Export logs in AdGuard
>    
>    * Mac: menu -> advanced -> export logs and system info
>    * Windows: tray menu -> advanced -> export logs and system info
> 8. Archive both files (logs and chrome-net-export)
> 9. Send them to `devteam@adguard.com`. Mention this issue there, and also tell us the exact URL of the page that failed to load.

Done and done. It was very easy replicated on multiple sites. I hope the logs provide you what you need.

**Comment by ameshkov** [comment] 2020-11-17 23:07
Haven't received anything yet. Just in case, forward it to `am at adguard.com` as well please.

**Comment by WorldIRC** [comment] 2020-11-17 23:08
> Haven't received anything yet. Just in case, forward it to `am at adguard.com` as well please.

Done

**Comment by ameshkov** [comment] 2020-11-17 23:12
Just in case, try "Automatic proxy" mode in AdGuard: settings -> network -> select mode -> automatic proxy

**Comment by WorldIRC** [comment] 2020-11-17 23:29
> Just in case, try "Automatic proxy" mode in AdGuard: settings -> network -> select mode -> automatic proxy

This may have worked.  I will monitor and advise accordingly.

**Comment by WorldIRC** [comment] 2020-11-17 23:44
So far so good!

**Comment by ameshkov** [comment] 2020-11-17 23:59
One more quick question to everyone - are you able to reproduce anything using Chrome Canary build?

**Comment by robertcope** [comment] 2020-11-18 00:17
I think I'm having a different issue, but it seems similar. In my case, "random" pages just don't load, they just sort of hang. Canary does not resolve it. I guess I should get logs and such for you.

**Comment by WorldIRC** [comment] 2020-11-18 00:18
> I think I'm having a different issue, but it seems similar. In my case, "random" pages just don't load, they just sort of hang. Canary does not resolve it. I guess I should get logs and such for you.

Yep I have this issue too.

**Comment by ameshkov** [comment] 2020-11-18 18:25
@robertcope thanks for the logs!

Mentioning your forum thread here so that we don't forget about it: https://forum.adguard.com/index.php?threads/chrome-87-breaks-adguard.40642/

**Comment by ameshkov** [comment] 2020-11-19 16:18
Hi everyone.

We just released nightly updates for Mac and Windows.

They don't fully solve this issue, but it improves the behavior. Now instead of hanging the problematic connections will fail immediately.

What's important, we added more logging for this specific case, and the logs now will help us understand what exactly is the problem.

Could you please update to AdGuard nightly version and collect logs again?

You can get a nightly build here: https://adguard.com/beta.html
Instruction: https://github.com/AdguardTeam/CoreLibs/issues/1374#issuecomment-729258396

**Comment by robertcope** [comment] 2020-11-19 16:21
New logs, running nightly.

[chrome-net-export-log.json.zip](https://github.com/AdguardTeam/CoreLibs/files/5568190/chrome-net-export-log.json.zip)
[adguard_logs_20201119041953.zip](https://github.com/AdguardTeam/CoreLibs/files/5568195/adguard_logs_20201119041953.zip)

**Comment by ameshkov** [comment] 2020-11-19 21:19
@robertcope thank you so much for the logs!

AdGuard for Mac v2.5.1.927 nightly is out and it is supposed to fix this issue.
AdGuard for Win fix is coming tomorrow.

**Comment by robertcope** [comment] 2020-11-19 21:22
Just tested it, seems to work! I'll let you know if I run into anything crazy.

**Comment by WorldIRC** [comment] 2020-11-19 23:26
This may be affecting Chrome Android too. Also v87.

**Comment by WorldIRC** [comment] 2020-11-19 23:28
> @robertcope thank you so much for the logs!
> 
> AdGuard for Mac v2.5.1.927 nightly is out and it is supposed to fix this issue.
> AdGuard for Win fix is coming tomorrow.

I'm on Beta release for Mac. When do you see that being updated?

**Comment by ameshkov** [comment] 2020-11-20 05:02
Most likely we'll roll out a hotfix to all channels today or on monday.

**Comment by snhv** [comment] 2020-11-20 15:57
It's fixed with today's update. Thanks. I thought it was Chrome bug so just switched to Firefox (Win 10).

**Comment by ruchern-chong** [comment] 2020-11-20 16:00
The latest stable update seemed to have fixed the problem. Will continue monitoring for a couple of days.

**Comment by ameshkov** [comment] 2020-11-20 17:44
> I thought it was Chrome bug so just switched to Firefox (Win 10).

Meh, now I feel bad for fixing it and not helping Firefox a little bit :)

**Closed** 2020-11-24 16:43 UTC
Labels: P2: High, Resolution: Fixed, Status: Resolved, compatibility
