### ISSUE TITLE
mega.nz - pdf viewer doesn't work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#480] opened 2018-09-12 22:48 UTC
@AdamWr commented on [Fri Sep 07 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2323)

### Steps to reproduce

1. Go here - https://mega.nz/#F!ZbZUCIaD!g7PbBp39Tr7mA1w2rEWpQg
2. Try to open any file.

### Expected behavior

Preview should works correctly.

### Actual behavior

Opening file cause an error.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/45230737-21806280-b2ca-11e8-9cc3-5691d7c16005.png)

</details>

### Your environment

* Environment name and version: Chrome 69.0.3497.81
* Operating system and version: Windows 10, v.1803, build 17134.254
* AdGuard nightly 6.4.1571.4417

**As a temporary solution I added this rule** - `@@||static.mega.co.nz/*/html/pdfViewer_$extension,jsinject,elemhide` - **to English filter, so please disable it before checking.**

**Comment by AdamWr** [comment] 2019-07-10 11:35
It seems that with latest nightly build (7.1.28.48(CL 1.4.78)) not only preview option is broken.

Steps to reproduce:
1. Go here - https://mega.nz/#!GeAT0SLQ!j5HrkoWI2wR-6xoUgsyaK0H0ZbltJb7J5EPGvXz7wBY

Website is broken.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/60965928-607eaa80-a317-11e9-81ab-4bf67666ef74.png)

</details>

Works fine with stable build.

**Comment by sfionov** [comment] 2019-07-19 12:03
@AdamWr Can't reproduce on the latest nightly 2866. What filters do you have?

**Comment by AdamWr** [comment] 2019-07-19 12:09
I can reproduce that issue (here - https://mega.nz/#!GeAT0SLQ!j5HrkoWI2wR-6xoUgsyaK0H0ZbltJb7J5EPGvXz7wBY) with just `AdGuard Base` filter enabled, but it also happens when I disable all modules (Ad Blocker, Stealth mode, Browsing security, Extension).
AG for Windows nightly 7.1.2866

**Comment by sfionov** [comment] 2019-07-19 12:27
Reproduced, may be caused by #999, we'll check it.

**Comment by AdamWr** [comment] 2019-07-19 12:28
Ok 👍 
Thank you for reply.

**Comment by vshlobinag** [comment] 2019-07-22 09:57
Fixed in core/pull-requests/1399

**Comment by AdamWr** [comment] 2019-08-07 13:44
I can cofirm that issue with broken website was fixed, I mean this one - https://github.com/AdguardTeam/CoreLibs/issues/480#issuecomment-510024556, but I still can reproduce the original one - https://github.com/AdguardTeam/CoreLibs/issues/480#issue-359680064
If I disable this rule:
`@@||static.mega.co.nz/*/html/pdfViewer_$extension,jsinject,elemhide`
go here https://mega.nz/#F!ZbZUCIaD!g7PbBp39Tr7mA1w2rEWpQg and try to open any file, then file won't loads.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/62627111-0a5a5280-b929-11e9-8839-ae319d18360f.png)

</details>

It also happens when I disable all modules (Ad Blocker, Stealth mode, Browsing security, Extensions).
AdGuard for Windows nightly 7.1.2880.38(CL 1.4.133)

**Comment by ameshkov** [comment] 2019-08-07 13:56
Well, this is okay that hashes do not match as AG adds cosmetic rules to the file.

> It also happens when I disable all modules (Ad Blocker, Stealth mode, Browsing security, Extensions).

If you have debug-level logging enabled, AG adds some parsing stats to the end of the page

**Comment by AdamWr** [comment] 2019-08-07 14:00
>Well, this is okay that hashes do not match as AG adds cosmetic rules to the file.

Okay, I understand.

>If you have debug-level logging enabled, AG adds some parsing stats to the end of the page

I have logging level set to "Default".

**Comment by ameshkov** [comment] 2019-08-07 14:03
> I have logging level set to "Default".

Please try opening the HTML page with AG and without it and check is there any difference?

**Comment by AdamWr** [comment] 2019-08-07 14:10
Yes, there is a difference.
<details><summary>AdGuard enbaled with all modules disabled</summary>

![image](https://user-images.githubusercontent.com/29142494/62629460-750d8d00-b92d-11e9-9835-9eefc6843531.png)

</details>

<details><summary>AdGuard disabled</summary>

![image](https://user-images.githubusercontent.com/29142494/62629492-82c31280-b92d-11e9-9b8f-6758d8ac3e94.png)

</details>

If I'm not wrong, AdGuard ExtendedCss script is injected.

**Comment by ameshkov** [comment] 2019-08-07 14:12
Thank you!

Got it, so the problem is that even when all modules are disabled, AG still injects the content script.

### Steps to reproduce:

1. Disable all AdGuard modules in the interface (either Mac or Win), but keep it enabled
2. Go to https://mega.nz/#F!ZbZUCIaD!g7PbBp39Tr7mA1w2rEWpQg
3. Try to open any file.

### Expected result
No issues

### Actual result
AG injects the content script to one of the loaded HTML pages -> causes "file is corrupt" issue

Reopened and re-assigned to v1.5.

**Comment by vshlobinag** [comment] 2019-08-13 09:41
Can't reproduce. Try clean browser cache.

**Comment by AdamWr** [comment] 2019-08-13 10:05
I can easily reproduce it in incognito/private mode in Chrome/Opera/Vivaldi/Edge/Firefox, so I think it's not related to browser cache.

I think the problem is that AdGuard is injecting content script even if all modules are disabled.

**Comment by vshlobinag** [comment] 2019-08-13 10:14
Reproduced with disabled @@||static.mega.co.nz/*/html/pdfViewer_$extension,jsinject,elemhide in incognito in Chrome

**Comment by sfionov** [comment] 2019-08-13 10:23
@ameshkov The problem is that CoreLibs doesn't know such synthetic case as "all filters are disabled". It will inject content-script into any HTML page without `elemhide,jsinject,extension` exception because at least generic css rules and generic js rules must be injected. They selected when content-script is queried, not when content-script is injected to page.

Anyway, this case is for filters because it is ajax request for part of HTML page. All such rare cases should be handled in filters.

**Comment by ameshkov** [comment] 2019-08-13 10:27
Well, this is a minor issue indeed, but I guess it shouldn't be hard to detect a situation when the CL configuration is empty (no filters, stealth mode disabled, no userscripts) and no injections are necessary.

**Closed** 2020-01-27 12:24 UTC
Labels: P4: Low, bug
