### ISSUE TITLE
generichide/elemehide doesn't work with subdocument exception

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1527] opened 2021-10-04 20:48 UTC
Steps to reproduce:
1. Add these rules:
```
example.org##body
@@||example.org^$elemhide
@@$subdocument,domain=example.org
```
2. Go to - https://example.org/

### Expected behavior
`example.org##body` should be disabled by `@@||example.org^$elemhide`

### Actual behavior
`example.org##body` is not disabled by `elemhide` if there is exception with `subdocument` modifier.

AdGuard for Windows 7.7 nightly 24 (build 3708, CL 1.8.195)

**Comment by sxgunchenko** [comment] 2021-10-08 16:16
It seems we can only fix this for cases where a Sec-Fetch-Dest header is present, otherwise, CoreLibs cannot distinguish between a request to a subdocument and a request to a document

**Comment by sxgunchenko** [comment] 2021-11-16 09:43
This one looks like a duplicate of https://github.com/AdguardTeam/CoreLibs/issues/1382

**Closed by sxgunchenko** 2021-11-16 09:43 UTC
Labels: bug, P3: Medium, Version: CoreLibs v1.9
