### ISSUE TITLE
HTTPS filtering doesn't work on zebramo.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#179] opened 2018-02-28 12:25 UTC
Steps to reproduce

1. Enable Social media filter
2. Go here - https://zebramo.com/products/149644154/vichy-gunes-kremi
3. Social widget should be hidden

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/36787364-34ad8116-1c8a-11e8-8f10-77722fd60b86.png)

</details>
<br>

AdGuard for Windows 6.2.437.2171/6.3.773.2821

https://github.com/AdguardTeam/AdguardFilters/issues/12333

**Comment by ameshkov** [comment] 2018-05-30 08:19
Caused by OCSP:
`OCSP response verification for zebramo.com returned with status 13 (OCSP response is not current)`

**Comment by szolin** [comment] 2018-08-01 11:34
Can't reproduce this issue anymore.  Now it works on Android and Linux with different browsers.  Probably it was a problem with the site, but it's fixed now.

**Closed by szolin** 2018-08-01 11:34 UTC
Labels: P4: Low, bug
