### ISSUE TITLE
re-store.ru issue

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/CoreLibs#1084] opened 2019-08-15 08:22 UTC
1. Open https://re-store.ru in Safari on Mac (or with user agent **Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A** )(standard one for Safari under Mac in Chrome). No issue with other user agents so far
2. Either complete white page and no content is loaded or "waiting for local.adguard.org".

When the site is added to HTTPS exclusions it works fine, with document exclusion not. Also shutting down AdGuard for Windows completely loads the site fine with mentioned user agent.

https://github.com/AdguardTeam/AdguardFilters/issues/38242

**Comment by ameshkov** [comment] 2019-08-15 08:23
Hm, cannot reproduce on the latest nightly build of AG.

Which version have you tried?

**Comment by BlazDT** [comment] 2019-08-15 08:23
7.1.2885 NIGHTLY (CL 1.4.133)

**Comment by ameshkov** [comment] 2019-08-15 08:23
Ah, my bad, the issue is there on Safari

**Comment by ameshkov** [comment] 2019-08-15 08:25
Looks EXACTLY as the issue with #674, it seems they're using the flawed anti-ddos approach. We'll address this in v1.5

**Comment by sfionov** [comment] 2019-12-18 14:57
Merged into #1223

**Closed** 2019-12-18 14:57 UTC
Labels: P3: Medium, bug, compatibility
