### ISSUE TITLE
monzo.com - CSP Issue

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/CoreLibs#1010] opened 2019-07-08 12:28 UTC
Original report:
https://github.com/AdguardTeam/AdguardFilters/issues/36102
Main AdGuard modules are disabled.
<details><summary>Screenshot:</summary>

![Снимок экрана 2019-07-08 в 15 17 44](https://user-images.githubusercontent.com/33488229/60809665-deb24400-a193-11e9-9288-2b655c17b2f0.png)
</details><br/>

`@@||monzo.com^$csp` does not work.
Only helps disable protection `@@||monzo.com^$document`

**Comment by sfionov** [comment] 2019-07-08 12:41
Duplicate of #983, fixed already

**Closed by sfionov** 2019-07-08 12:41 UTC
Labels: P2: High, bug

**Comment by Alex-302** [comment] 2019-07-08 12:54
@sfionov is not it fixed in current nightly build?
