### ISSUE TITLE
radar.cloudflare.com - broken website

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/CoreLibs#1730] opened 2023-02-25 10:53 UTC
@adguard-bot commented on [Fri Feb 24 2023](https://github.com/AdguardTeam/AdguardFilters/issues/143916)

### Issue URL (Incorrect Blocking)
 [https://radar.cloudflare.com/ir](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fradar.cloudflare.com%2Fir)
### Comment
Username: @aliafshany
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/P11UXOe.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/OxGRkJR.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.10.0.1239+nightly
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `quic://dns.adguard-dns.com`<br>filters: `https://filters.adtidy.org/mac_v2/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>Liste AR, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Persian Blocker
Userscripts: | AdGuard+Popup+Blocker+(Beta)+(url:+https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js),<br>AdGuard+Extra+(Beta)+(url:+https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js),<br>Web+of+Trust+(Beta)+(url:+https://userscripts.adtidy.org/beta/adguard-wot/1.0/wot.user.js)

**Comment by AdamWr** [comment] 2023-02-25 10:55
Before checking, please add this rule:
```adblock
@@||radar.cloudflare.com^$elemhide,extension,content,badfilter
```
to user rules.

I'm not sure, but it might be related to this - https://github.com/AdguardTeam/CoreLibs/issues/492

**Comment by aliafshany** [comment] 2023-02-25 10:59
@AdamWr 
it didn't help
i cleared the cache, but no luck

**Comment by AdamWr** [comment] 2023-02-25 11:03
What exactly didn't help?
Did you add this rule:
```adblock
@@||radar.cloudflare.com^$elemhide,extension,content
```
to user rules?

**Comment by aliafshany** [comment] 2023-02-25 11:05
first i added this rule:
`@@||radar.cloudflare.com^$elemhide,extension,content,badfilter`
it didn't work
after that I tried this one:
`@@||radar.cloudflare.com^$elemhide,extension,content`

the problem is solved now.
thanks

**Comment by AdamWr** [comment] 2023-02-25 11:13
It looks like a `CoreLibs` issue, maybe related to this - https://github.com/AdguardTeam/CoreLibs/issues/492 (I'm not sure), so I have moved the issue from filters repository here.
The first rule (with `badfilter`) was provided to reproduce issue.

I have already added `@@||radar.cloudflare.com^$elemhide,extension,content` to `AdGuard Base filter`, but filters update will be available in about 1-2 hours.
Thank you for your reply.

**Comment by grumaxxx** [comment] 2023-05-30 10:58
@AdamWr Yes, you are right, it is because of the problem discussed in #492. Because even if you add a rule `radar.cloudflare.com###Test`, the styles are not displayed correctly on the site. Perhaps we should go back to the original problem. 
I will close this one as a duplicate.

**Closed** 2023-05-30 10:59 UTC
Labels: duplicate, Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.12, Priority: P4
