### ISSUE TITLE
re-store.ru is broken by AdGuard

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#1125] opened 2019-09-16 08:55 UTC
Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/40541

Actual behavior: blank page.

Reproduced on MacOS only. Exclusions don't help.

AdGuard 2.1.2.595

Not sure, but it seems not related to https://github.com/AdguardTeam/CoreLibs/issues/1124

**Comment by sfionov** [comment] 2019-09-16 08:56
Duplicate of #1084

**Closed by sfionov** 2019-09-16 08:56 UTC
Labels: Mac, bug
