### ISSUE TITLE
www.gulliver.ru is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#825] opened 2019-03-27 16:15 UTC
AdGuard 2.0.0.524 / Cl 1.3.223

Actual behavior:

<details>

![image](https://user-images.githubusercontent.com/8361299/55092959-31bc2b80-50bc-11e9-8c8b-8871d75ae331.png)

</details>

Original issue:
https://forum.adguard.com/index.php?threads/www-gulliver-ru.31344/#

**Comment by sfionov** [comment] 2019-03-27 19:10
Duplicate of #823. Fixed in CL1.3.241.

**Closed by sfionov** 2019-03-27 19:10 UTC
Labels: Check with CoreLibs, Mac, bug
