### ISSUE TITLE
UserScript in ADG GM_setValue can not work

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/CoreLibs#1450] opened 2021-05-12 11:32 UTC
@ilvjyw commented on [Wed May 05 2021](https://github.com/AdguardTeam/AdguardForWindows/issues/3777)

ADG Version 7.6 nightly 41 (build 3586, CL 1.7.221)
win10 x64  Chromium 86

**Bug recurrence**
1. Setting like this: 
**Settings--Advanced Settings--Filter localhost**

2. Add "test.js" to Extensions in ADG
`// ==UserScript==
// @name         test
// @version      0.1
// @description  try to take over the world!
// @author       You
// @icon         https://www.google.com/s2/favicons?domain=cnblogs.com
// @homepageURL https://xxxx.com/
// @match http://*/*
// @match https://*/*
// @grant GM_getValue
// @grant GM_setValue
// @grant GM_deleteValue
// @grant GM_listValues
// @grant GM_getResourceURL
// @grant unsafeWindow
// @run-at document-start
// ==/UserScript==
(function() {
    'use strict';
    
    // Your code here...
    var localStorage = {
    getItem : function (name, defaultValue) {
        return GM_getValue(name, defaultValue)
    },
    setItem : function (name, value) {
        return GM_setValue(name, value)
    },
    removeItem : function (name) {
        return GM_deleteValue(name)
    },
    listItem : function () {
        return GM_listValues()
    }
};
   localStorage.setItem("test","日你大爷");
   console.log(localStorage.getItem("test"));
    // var a = {
    //    'name': '大象笔记'
    //};

    //GM_setValue('zw_test', a);
    //console.log(GM_getValue('zw_test'));
    //console.log(GM_getValue('zw_test').name);
})();`

3. Open chrome--any site  F12 Console log

GET https://local.adguard.org/adguard-ajax-api/api?type=gm-set-value&unique_name=test&variable_key=test&variable_value=%5BLString%3B%E6%97%A5%E4%BD%A0%E5%A4%A7%E7%88%B7&synchronous=false&sn=0b0f21ee1fa4306326bdf9a762be2138878b90c5e60c134e36a76e8760601c7e 400 (Bad request)

WebSocket connection to 'wss://local.adguard.org/adguard-ws-api/api' failed: Error during WebSocket handshake: Unexpected response code: 400

4. UserScript in ADG GM_setValue can not work
Please fix!

**Comment by sfionov** [comment] 2021-05-12 11:59
Duplicate of #1446

**Closed by sfionov** 2021-05-12 11:59 UTC
