### ISSUE TITLE
m.vz.ru - article can't be loaded

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/CoreLibs#471] opened 2018-09-10 08:34 UTC
@adguard-bot commented on [Thu Sep 06 2018](https://github.com/AdguardTeam/AdguardFilters/issues/22103)

### Issue URL (Incorrect Blocking)
[https://m.vz.ru/news/2018/9/6/940661.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.vz.ru%2Fnews%2F2018%2F9%2F6%2F940661.html)
### Comment
Username: @FelagundHi
> Пои включённой фильтрации постоянная загрузка статьи.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](http://res.cloudinary.com/adguard/image/private/s--RDOPxx4Z--/v1536261241/f19tumfbyft9cmgup22r.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 8.0.0
AdGuard version: | 2.12.214η
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | AdGuard Russian,<br>AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Spyware,<br>AdGuard Social Media

**Comment by Alex-302** [comment] 2018-09-10 08:36
Статья не загружается, пока не добавишь исключение:
`@@https://m.vz.ru/news/2018/9/6/940661.html^$document`
отключение фильтров не помогает.  На других платформах не повторяется.

**Comment by ameshkov** [comment] 2018-09-10 08:58
@sfionov the issue is caused by mere content-script injection

**Comment by ameshkov** [comment] 2018-09-10 09:02
@sfionov AG injects into an XHR response: `https://m.vz.ru/api/news_by_id/941076.xml `

**Comment by Alex-302** [comment] 2018-09-10 09:08
on my end I see no injections to this XHR (and no `adguard` in search results in content)

**Comment by ameshkov** [comment] 2018-09-10 09:19
We have to improve the HTML detection algorithm.

If response content type is XML, we must look for the following markers **only**: `doctype`,  `xml-stylesheet`.

**Comment by sfionov** [comment] 2018-09-10 09:57
Fixed in core/pull-requests/655

**Closed by sfionov** 2018-09-10 09:57 UTC
Labels: Android, Check with CoreLibs, bug
