### ISSUE TITLE
High CPU usage while uploading files to filehosters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/CoreLibs#790] opened 2019-03-09 15:45 UTC
@skipik commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490)

![111](https://user-images.githubusercontent.com/24621645/54071296-a816fc00-427b-11e9-973a-6a5aa0406124.png)

I don't want to share logs here. Please give me e-mail where I can send them to. Thanks.
P.S. My AdGuard version is the latest nightly.

---

@Alex-302 commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471171251)

@skipik 
![image](https://user-images.githubusercontent.com/8361299/54071335-e9a3a900-4273-11e9-9c66-dd91208a8f00.png)

---

@skipik commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471171411)

@Alex-302 Поддержка принимает отчеты о 7 версии уже? Можно писать на русском?

---

@Alex-302 commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471171487)

Ну в комменте укажи ссылку на задачу, а сюда - номер тикета.

---

@Alex-302 commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471171812)

А скорость отдачи у тебя не режет? На upload.ee, например, вот так:
Без Адгарда
![image](https://user-images.githubusercontent.com/8361299/54071379-7c444800-4274-11e9-8ad5-3617c0a92d2b.png)
с Адгардом
![image](https://user-images.githubusercontent.com/8361299/54071396-bdd4f300-4274-11e9-9f52-e9198d8006d7.png)

---

@skipik commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471172065)

> А скорость отдачи у тебя не режет?

Режет. Причём как и у вас - то есть в разы.

---

@skipik commented on [Sat Mar 09 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2490#issuecomment-471172801)

Отправил в саппорт логи, номер тикета: 2135818.

**Comment by sxgunchenko** [comment] 2019-06-24 08:11
core/pull-requests/1334

**Comment by TheHasagi** [comment] 2019-06-28 09:29
Unable to reproduce the issue.

**Comment by Alex-302** [comment] 2019-06-28 12:52
reproduced
![image](https://user-images.githubusercontent.com/8361299/60343439-aa34d000-99bc-11e9-9c28-42aefa13283f.png)

**Comment by Alex-302** [comment] 2019-06-28 12:54
and cannot upload to this site

**Comment by sxgunchenko** [comment] 2019-06-28 14:04
the fix was released in CL version 1.4.35, but AdGuard 7.1.2818 uses CL of version 1.4.32

**Closed** 2019-08-07 13:06 UTC
Labels: P2: High, Windows, bug
